var zoneArray = new Array(79);

zoneArray[1]="-12"; //International Date Line West
zoneArray[2]="-11"; //Midway Island
zoneArray[3]="-10"; //Hawaii
zoneArray[4]="-9"; //Alaska
zoneArray[5]="-8"; //Pacific Time (US &amp; Canada), Tijuana
zoneArray[6]="-7"; //Arizona
zoneArray[7]="-7"; //Chihuahua, La Paz, Mazatlan
zoneArray[8]="-7"; //Mountain Time (US &amp; Canada)
zoneArray[9]="-6"; //Central America
zoneArray[10]="-6"; //Central Time (US &amp; Canada)
zoneArray[11]="-6"; //Guadalajara, Mexico City, Monterrey
zoneArray[12]="-6"; //Saskatchewan
zoneArray[13]="-5"; //Bogota, Lima, Quito, Indiana (East)
zoneArray[14]="-5"; //Eastern Time (US &amp; Canada)
zoneArray[15]="-4.5"; //Caracas
zoneArray[16]="-4"; //Georgetown, La Paz
zoneArray[17]="-4"; //Atlantic Time (Canada)
zoneArray[18]="-4"; //Santiago
zoneArray[19]="-3.5"; //Newfoundland
zoneArray[20]="-3"; //Brasilia
zoneArray[21]="-3"; //Buenos Aires
zoneArray[22]="-3"; //Greenland
zoneArray[23]="-2"; //Mid-Atlantic
zoneArray[24]="-1"; //Azores
zoneArray[25]="-1"; //Cape Verde Is.
zoneArray[26]="0"; //Casablanca, Monrovia
zoneArray[27]="0"; //Greenwich Mean Time : Dublin, Edinburgh, Lisbon, London
zoneArray[28]="1"; //Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
zoneArray[29]="1"; //Belgrade, Bratislava, Budapest, Ljubljana, Prague
zoneArray[30]="1"; //Brussels, Copenhagen, Madrid, Paris
zoneArray[31]="1"; //Sarajevo, Skopje, Warsaw, Zagreb
zoneArray[32]="1"; //West Central Africa
zoneArray[33]="2"; //Athens, Istanbul, Minsk
zoneArray[34]="2"; //Bucharest
zoneArray[35]="2"; //Cairo
zoneArray[36]="2"; //Harare, Pretoria
zoneArray[37]="2"; //Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius
zoneArray[38]="2"; //Jerusalem
zoneArray[39]="3"; //Baghdad
zoneArray[40]="3"; //Kuwait, Riyadh
zoneArray[41]="3"; //Nairobi
zoneArray[42]="3.5"; //Tehran
zoneArray[43]="4"; //Abu Dhabi, Muscat
zoneArray[44]="4"; //Baku, Tbilisi, Yerevan
zoneArray[45]="4"; //Moscow, St. Petersburg, Volgograd
zoneArray[46]="4.5"; //Kabul
zoneArray[47]="5"; //Islamabad, Karachi, Tashkent
zoneArray[48]="5.5"; //Chennai, Kolkata, Mumbai, New Delhi
zoneArray[49]="5.5"; //Sri Jayawardenepura
zoneArray[50]="5.75"; //Kathmandu
zoneArray[51]="6"; //Astana, Dhaka
zoneArray[52]="6"; //Ekaterinburg
zoneArray[53]="6.5"; //Rangoon
zoneArray[54]="7"; //Almaty, Novosibirsk
zoneArray[55]="7"; //Bangkok, Hanoi, Jakarta
zoneArray[56]="8"; //Krasnoyarsk
zoneArray[57]="8"; //Beijing, Chongqing, Hong Kong, Urumqi
zoneArray[58]="8"; //Kuala Lumpur, Singapore
zoneArray[59]="8"; //Perth
zoneArray[60]="8"; //Taipei
zoneArray[61]="8"; //Ulaan Bataar
zoneArray[62]="9"; //Irkutsk
zoneArray[63]="9"; //Osaka, Sapporo, Tokyo
zoneArray[64]="9"; //Seoul
zoneArray[65]="9.5"; //Adelaide
zoneArray[66]="9.5"; //Darwin
zoneArray[67]="10"; //Brisbane
zoneArray[68]="10"; //Canberra, Melbourne, Sydney
zoneArray[69]="10"; //Guam, Port Moresby
zoneArray[70]="10"; //Hobart
zoneArray[71]="10"; //Yakutsk
zoneArray[72]="11"; //Solomon Is., New Caledonia
zoneArray[73]="11"; //Vladivostok
zoneArray[74]="12"; //Magadan
zoneArray[75]="12"; //Auckland, Wellington
zoneArray[76]="12"; //Fiji, Kamchatka, Marshall Is.
zoneArray[77]="13"; //Nuku'alofa
zoneArray[78]="13"; //Samoa

