{

	"Home": "홈",
	"Settings": "설정",
	"Management": "관리",
	"Internet(WAN)": "인터넷 (WAN)",
	"Wireless(Wi-Fi)": "무선(Wi-Fi)",
	"Network(LAN)": "네트워크 (LAN)",
	"Wizard": "설치 마법사",
	"SharePort": "SharePort",
	"mydlink": "mydlink",
	"Firewall Settings": "방화벽 설정",
	"Virtual Server": "가상 서버",
	"Port Forwarding": "포트 포워딩",
	"Website Filter": "웹 사이트 필터",
	"Static Route": "고정 경로",
	"Disabled": "사용 안 함",
	"Enabled": "사용 함",
	"Advanced": "고급",
	"System Admin": "시스템 관리자",
	"COPYRIGHT": "COPYRIGHT &copy; 2015 D-Link",


	"There is unsaved data on this page. Do you want to abandon it?": "변경된 사항이 적용되지 않습니다. 계속 하시겠습니까?",
	"Remaining": "진행 중",
	"Not Available": "사용 할 수 없습니다.",
	"Go to settings": "설정 화면으로 이동",
	"Click here for help.": "도움말을 확인하시려면 이곳을 클릭하여 주십시오.",
	"Type the characters you see in the picture below.": "아래 보이는 그림문자를 입력하여 주십시오.",
	"Unsecured": "안전하지 않음",
	"<< Computer Name": "<< 컴퓨터 이름",
	"<< Application Name": "<< 응용 프로그램 이름",
	"Host": "호스트",
	"Guest": "게스트",


	"Model Name": "모델명",
	"Hardware Version": "하드웨어 버전",
	"Firmware Version": "펌웨어 버전",
	"Language": "언어",
	"Admin Password": "관리자 비밀번호",
	"Log In": "로그인",
	"To access your storage with SharePort Web Access,": "SharePort 웹액세스로 스토리지에 접속하려면,",
	"click here.": "이곳을 클릭하여 주십시오.",
	"Invalid password, please try again.": "비밀번호가 올바르지 않습니다. 다시 확인하여 주십시오.",
	"Invalid password or captcha, please try again.": "비밀번호 혹은 보안문자가 올바르지 않습니다. 다시 확인하여 주십시오.",
	"The Private Browsing feature of Safari is incompatible with this device's interface. You will need to disable Private Browsing to log in.": "사파리의 개인 정보 보호 브라우징 기능이 장치의 인터페이스와 호환되지 않습니다. 로그인 할 개인 정보 보호 브라우징을 비활성화 해야합니다.",
	"License Agreement": "라이선스 동의",
	"To access device management,": "장치 관리에 접속하려면,",


	"Current Status": "현재 상태",
	"Click on any item in the diagram for more information.": "자세한 내용은 메뉴에서 해당 항목을 클릭하시기 바랍니다.",
	"Setup Wizard": "설치 마법사",
	"Router": "공유기",
	"Internet": "인터넷",
	"NULL": "없음",
	"LAN": "LAN",
	"WAN": "WAN",
	"Router IP Address": "공유기 IP 주소",
	"MAC Address": "MAC 주소",
	"<< MAC Address": "<< MAC 주소",
	"Wi-Fi 2.4GHz": "2.4GHz Wi-Fi",
	"Wi-Fi 5GHz": "5GHz Wi-Fi",
	"Guest Zone 2.4GHz": "2.4GHz 게스트 존",
	"Guest Zone 5GHz": "5GHz 게스트 존",
	"IP Address": "IP 주소",
	"Subnet Mask": "서브넷 마스크",
	"Default Gateway": "기본 게이트웨이",
	"Available Space": "사용 가능 공간",
	"Total Space": "총 공간",
	"Service Name": "서비스 이름",
	"Ethernet Device": "이더넷 장치",
	"Wi-Fi Clients": "Wi-Fi 클라이언트",
	"USB Device": "USB 장치",
	"USB Name": "USB 이름",
	"Status": "상태",
	"Wi-Fi Name (SSID)": "Wi-Fi 이름 (SSID)",
	"Password": "비밀번호",
	"IPv6 Connection Type": "IPv6 연결 유형",
	"Primary IPv6 DNS Server": "기본 IPv6 DNS 서버",
	"Secondary IPv6 DNS Address": "보조 IPv6 DNS 주소",
	"LAN IPv6 Link-Local Address": "LAN IPv6 Link-Local 주소",
	"DHCP-PD": "DHCP-PD",
	"IPv6 Network Assigned by DHCP-PD": "DHCP-PD에 의해 할당 된 IPv6 네트워크",
	"LAN IPv6 Address": "LAN IPv6 주소",
	"Guest Zone": "게스트 존",
	"Connection Type": "연결 유형",
	"Network Status": "네트워크 상태",
	"Connection Uptime": "연결 유지 시간",
	"Primary DNS Server": "기본 DNS 서버",
	"Secondary DNS Server": "보조 DNS 서버",
	"Release IP Address": "IP 주소 연결 해제",
	"Renew IP Address": "IP 주소 갱신",
	"Disconnect": "연결 끊기",
	"Connect": "연결",
	"Ignore": "무시",
	"Connected": "연결 됨",
	"Connecting": "연결 중…",
	"Disconnected": "연결 끊김",
	"DHCP": "Dynamic IP (DHCP)",
	"Static": "Static IP (Static)",
	"DHCPPPPoE": "유동 IP (PPPoE)",
	"StaticPPPoE": "Static IP (PPPoE)",
	"DynamicPPTP": "Dynamic IP (PPTP)",
	"StaticPPTP": "Static IP (PPTP)",
	"DynamicL2TP": "Dynamic IP (L2TP)",
	"StaticL2TP": "Static IP (L2TP)",
	"DsLite": "DS-Lite",
	"A new firmware is available! Do you want to download and upgrade the firmware?": "새로운 펌웨어를 사용 할 수 있습니다. 펌웨어 업그레이드를 진행하시겠습니까?",
	"Your changes are being saved, and the device will need to reboot.": "설정을 저장하고 있습니다. 일부 설정은 장비가 재부팅된 이후에 적용됩니다.",
	"Internet Connected": "인터넷 연결 됨",
	"Internet Disconnected": "인터넷 연결 끊김",
	"New firmware available": "새로운 펌웨어가 있습니다.",
	"Get Help": "도움말",
	"Connected Clients": "연결된 단말",
	"Click on the pencil icon to give the device a name to make it easy to identify.": "장치명을 변경하려면 [연필] 아이콘을 클릭하여 주십시오.",
	"You can block a device from accessing your network at all times or according to a schedule by using the Block dropdown box.": "설정된 스케줄에 따라 장치의 네트워크 접속을 차단할 수 있습니다.",
	"There are no devices available": "사용 할 수 있는 장치가 없습니다.",
	"IPv4 Network": "IPv4 네트워크",
	"IPv6 Network": "IPv6 네트워크",
	"Cable Status": "케이블 연결 상태",
	"Click to repair": "복구",
	"No USB device detected": "USB 장치 없음",
	"Link-Local Address": "Link-Local 주소",
	"Router IPv6 Address": "공유기 IPv6 주소",
	"Assigned Prefix": "할당 된 Prefix",
	"IPv6": "IPv6",
	"IPv4": "IPv4",
	"Limited Connection": "제한된 연결",
	"Release": "해제",
	"Renew": "갱신",
	"6rd": "6rd",
	"Parental Control": "자녀 보호",


	"Welcome": "환영합니다",
	"This wizard will guide you through a step-by-step process to configure your new D-Link device.": "마법사는 단계별 과정을 통해 새로운 D-Link 장치를 구성 할 수 있도록 안내 할 것 입니다.",
	"Step 1: Install your device": "1 단계 : 장치 설치",
	"Step 2: Configure your Network and Wi-Fi settings": "2 단계 : 네트워크 및 Wi-Fi 설정 구성",
	"Step 3: Set your router password": "3 단계 : 관리자 비밀번호 설정",
	"Step 4: Set up mydlink service": "4 단계 : mydlink 서비스 설정",
	"Your Device": "장치",
	"Cable/xDSL Broadband Modem": "케이블/xDSL 광대역 모뎀",
	"DHCP Connection (Dynamic IP Address)": "DHCP 연결 (유동 IP 주소)",
	"Choose this if your Internet connection automatically provides you with an IP Address. Most Cable Modems use this type of connection.": "IP 주소를 자동으로 제공받는 인터넷 연결은 이 옵션을 선택하세요. 대부분의 케이블 모뎀은 이 연결 유형을 사용합니다.",
	"Username/Password Connection (PPPoE)": "사용자 이름 / 비밀번호 연결 (PPPoE)",
	"Choose this option if your Internet connection reguires a username and passowrd to get online. Most DSL modems use this connection type of connection.": "온라인 연결을 위해 사용자 이름과 비밀번호를 입력하는 인터넷 연결은 이 옵션을 선택하세요. 대부분의 DSL 모뎀은 이 연결 유형을 사용합니다.",
	"Static IP Address Connection": "고정 IP 주소 연결",
	"Choose this option if your Internet Setup Provider provided you with IP Address information that has to be manually configured.": "인터넷 공급자(ISP)로부터 고정 IP 주소를 할당받은 경우 이 옵션을 선택하여 주십시오.",
	"Username": "사용자 이름",
	"Gateway Address": "게이트웨이 주소",
	"Primary DNS Address": "기본 DNS 주소",
	"Secondary DNS Address": "보조 DNS 주소",
	"2.4GHz Wi-Fi Network Name": "2.4GHz Wi-Fi 네트워크 이름",
	"5GHz Wi-Fi Network Name": "2.4GHz Wi-Fi 네트워크 이름",
	"The Wi-Fi Network Name is up to 32 characters. You will need to join your Wi-Fi network using this Network Name (SSID).": "Wi-Fi 네트워크 이름(SSID)은 32자 까지 설정 가능합니다. 이 네트워크 이름(SSID)으로 Wi-Fi 네트워크에 연결 할 수 있습니다.",
	"Wi-Fi Password": "Wi-Fi 비밀번호",
	"2.4GHz Wi-Fi Password": "2.4GHz Wi-Fi 비밀번호",
	"5GHz Wi-Fi Password": "5GHz Wi-Fi 비밀번호",
	"The password must contain at least 8 characters. You will need to join your Wi-Fi network using this password.": "비밀번호는 반드시 8자 이상 입력하시기 바랍니다. 이 비밀번호를 사용하여 Wi-Fi 네트워크에 연결할 수 있습니다.",
	"Device Admin Password": "장치 관리자 비밀번호",
	"This device is mydlink-enabled, which allows you to remotely monitor and manage your network through the mydlink.com website, or through the mydlink mobile app.": "이 장치는 mydlink 웹사이트 또는 모바일용 mydlink 어플을 통해 네트워크 상태를 모니터링하고 관리할 수 있습니다.",
	"You can register this device with your existing mydlink account. If you do not have one, you can create one now.": "기존 mydlink 계정으로 등록할 수 있습니다. 계정이 없다면, 지금 생성할 수 있습니다.",
	"Do you have an existing mydlink account?": "기존 mydlink 계정을 가지고 있습니까?",
	"Yes, I have a mydlink account": "네. Mydlink 계정을 가지고 있습니다.",
	"No, I want to create a new mydlink account": "아니오, 새로운 mydlink 계정을 등록하겠습니다.",
	"E-mail Address (Account Name)": "이메일 주소 (계정 이름)",
	"First Name": "이름",
	"Last Name": "성",
	"I accept the mydlink": "mydlink를 수용합니다. <a href=\"https://www.mydlink.com/termsOfUse\"target=\"_blank\">조건.</a>",
	"Connect to the Wi-Fi network from your mobile device or PC": "모바일 장치나 PC에서 Wi-Fi 네트워크에 연결",
	"1.Please go to Settings > Wi-fi, and choose": "1. 설정에서 무선 메뉴로 이동 후",
	"from the list of Wi-Fi network services.": "Wi-Fi 네트워크 서비스 목록에서 선택 하십시오.",
	"2.Enter the password you just setup when prompted.": "2. 메시지가 표시되면 설정한 비밀번호를 입력 하십시오.",
	"Wi-Fi Client": "Wi-Fi 클라이언트",
	"Save": "저장",
	"Please wait": "잠시 기다려주시기 바랍니다.",
	"Configure Your Internet Connection": "인터넷 연결 설정",
	"Detecting Internet Connection": "인터넷 연결을 감지 중",
	"Install": "설치",
	"Please plug one end of the Ethernet cable included with your device into the port labeled INTERNET on your device. Plug the other end of this cable into the Ethernet port on your DSL or cable broadband modem, and power cycle the modem.": "이더넷 케이블의 한 쪽을 공유기 뒷면 인터넷 포트에 연결하고 다른 한 쪽을 DSL 또는 광대역 모뎀에 연결 후 모뎀의 전원을 껐다가 켜주시기 바랍니다.",
	"Please select your Internet connection type below": "인터넷 연결 유형을 선택하여 주십시오.",
	"PPPoE": "PPPoE",
	"To setup this Internet connection, you will need to have a User Name from your Internet Service Provider. If you do not have this information, please contact your ISP.": "이 인터넷 연결을 설정하려면, 인터넷 공급자(ISP)로 부터 제공받은 사용자 이름이 필요합니다. 이 정보가 없는 경우, 인터넷 공급 업체(ISP)에 문의하시기 바랍니다.",
	"Static IP": "고정 IP",
	"Dynamic IP (DHCP)": "유동 IP (DHCP)",
	"To set up this conncetion you will need to have a complete list of IP information by your Internet Service Provider. If you have a Static IP connection and do not have this information, please contact your ISP.": "이 인터넷 연결을 설정하려면, 인터넷 공급자(ISP)로 부터 제공받은 고정 IP 정보가 필요합니다. 고정 IP 정보가 없는 경우, 인터넷 공급 업체(ISP)에 문의하시기 바랍니다.",
	"Wi-Fi Settings": "Wi-Fi 설정",
	"By default, your new D-Link device does not have a password configured for administrator access to the Web-based configuration utility. To secure your new device, please create a password below.": "새로운 D-Link 장치는 기본적으로 관리자 페이지 접속 비밀번호가 설정되어 있지 않습니다. 보안을 위해 비밀번호를 설정하여 주십시오.",
	"Below is a summary of your Wi-Fi security and device password settings. Please make a note of your settings and click \"Next\".": "하단의 내용은 Wi-Fi 설정 및 관리자 암호 설정에 대한 내용입니다. 해당 내용을 메모해 두시면, 잊어버릴 경우 확인이 쉽습니다.",
	"Checking Your Internet Connectivity": "인터넷 연결을 확인 중 입니다.",
	"Checking Internet Connectivity": "인터넷 연결 확인 중",
	"mydlink Registration": "mydlink 등록 완료",
	"Congratulations": "축하합니다.",
	"Congratulations, your device has been configured. You can now connect to your Wi-Fi network by using the new Wi-Fi Network Name and Password you created.": "장치가 구성이 완료 되었습니다. 이제 새로 만든 Wi-Fi 네트워크 이름(SSID)과 비밀번호를 사용하여 Wi-Fi 네트워크에 연결할 수 있습니다.",
	"Back": "뒤로",
	"Next": "다음",
	"Skip": "건너뛰기",
	"Finish": "완료",
	"Registered": "등록 완료",
	"Unregistered": "등록 안됨",
	"Summary": "목록",
	"Use the same password for both networks": "동일한 비밀번호를 입력하여 주십시오",
	"Email or password field is required.": "이메일 혹은 비밀번호를 입력하여 주십시오.",


	"DHCP Renew": "DHCP 갱신",
	"DHCP Release": "DHCP 해제",
	"You may now use mydlink service with this device.": "이제 mydlink 서비스를 사용할 수 있습니다.",
	"2.4GHz Guest Zone": "2.4GHz 게스트 존",
	"5GHz Guest Zone": "5GHz 게스트 존",
	"Your changes are being saved, please wait...": "설정을 저장하고 있습니다. 잠시만 기다려 주십시오...",
	"Wi-Fi": "Wi-Fi",
	"View": "보기",
	"Desktop": "일반 PC",
	"Mobile": "모바일",
	"Wi-Fi Name": "이름",
	"2.4GHz Wi-Fi Name": "2.4GHz 와이파이 이름",
	"5GHz Wi-Fi Name": "5GHz 와이파이 이름",


	"Wi-Fi Clients (Guest Zone)": "Wi-Fi 단말(게스트 존))",
	"Click on a device to view more information about it, or click on the pencil icon to give the device a name to make it easy to identify. You can block a device from accessing your network always or according to a schedule by using the Block dropdown box.": "장치에 대한 정보를 확인하거나 장치 구분을 위한 이름 변경 설정을 하시려면 [연필] 아이콘을 클릭하시기 바랍니다. 자녀보호 기능을 통해 장치의 인터넷 사용 시간을 설정할 수 있습니다.",
	"Here, you can see a list of all devices connected through Wi-Fi. Click on a device to view more information about it, or click on the pencil icon to give the device a name to make it easy to identify. You can block a device from accessing your network always or according to a schedule by using the Block dropdown box.": "Wi-Fi에 연결되어 있는 장치 목록입니다. 해당 장치를 클릭하시면 자세한 정보를 보실 수 있습니다. 장치명을 변경하시려면, [연필] 아이콘을 클릭하여 입력하여 주십시오. 또한, 선택항목을 변경하여 해당 장치의 접속을 차단하실 수 있습니다.",
	"Vendor": "공급 업체",
	"Reserve IP": "예약 IP",
	"Access": "접속",
	"Allowed": "허용",
	"Blocked": "차단",
	"Your Wi-Fi network needs to be enabled in order to turn on Guest Zone network. Would you like to turn on both?": "게스트 존 네트워크를 사용하기 위해 Wi-Fi 네트워크를 활성화해야 합니다. 두 기능 모두 사용하시겠습니까?",


	"Use this section to configure your Internet Connection type. There are several connection types to choose from Static IP, DHCP, PPPoE, PPTP, L2TP, and DS-Lite. If you are unsure of your connection method, please contact your Internet Service Provider. Note:  If using the PPPoE option, you will need to remove or disable any PPPoE client software on your computers.": "이곳에서 인터넷 연결 유형을 설정할 수 있습니다. 고정 IP, DHCP, PPPoE, PPTP, L2TP, DS-Lite 등의 여러가지 인터넷 연결 유형 중에 선택할 수 있습니다. 만약 인터넷 연결 유형을 모르는 경우 인터넷 공급 업체(ISP)에 문의하시기 바랍니다. 참고사항 : PPPoE 옵션을 사용하는 경우, 컴퓨터에 있는 PPPoE 클라이언트 소프트웨어를 제거하거나 사용하지 않도록 설정하시기 바랍니다.",
	"Use this section to configure your Internet Connection type. There are several connection types to choose from Static IP, DHCP, PPPoE, PPTP, L2TP and DS-Lite. If you are unsure of your connection method, please contact your Internet service provider. Note: If using the PPPoE option, you will need to remove or disable any PPPoE client software on your computers.": "이곳에서 인터넷 연결 유형을 설정할 수 있습니다. 고정 IP, DHCP, PPPoE, PPTP, L2TP, DS-Lite 등의 여러가지 인터넷 연결 유형 중에 선택할 수 있습니다. 만약 인터넷 연결 유형을 모르는 경우 인터넷 공급 업체(ISP)에 문의하시기 바랍니다. 참고사항 : PPPoE 옵션을 사용하는 경우, 컴퓨터에 있는 PPPoE 클라이언트 소프트웨어를 제거하거나 사용하지 않도록 설정하시기 바랍니다.",
	"My Internet Connection is": "인터넷 연결 방식",
	"Host Name": "호스트 이름",
	"Mac Address Clone": "MAC 주소 복사",
	"PPTP IP Address": "PPTP IP 주소",
	"PPTP Server IP Address": "PPTP 서버 IP 주소",
	"PPTP Subnet Mask": "PPTP 서브넷 마스크",
	"PPTP Gateway IP Address": "PPTP 게이트웨이 IP 주소",
	"L2TP IP Address": "L2TP IP 주소",
	"L2TP Server IP Address": "L2TP 서버 IP 주소",
	"L2TP Subnet Mask": "L2TP 서브넷 마스크",
	"L2TP Gateway IP Address": "L2TP 게이트웨이 IP 주소",
	"MTU": "MTU",
	"Address Mode": "주소 모드",
	"Reconnect Mode": "재연결 방식",
	"Maximum Idle Time": "최대 유휴 시간",
	"DS-Lite Configuration": "DS-Lite 설정",
	"DS-Lite DHCPv6 Option": "DS-Lite DHCPv6 옵션",
	"Manual Configuration": "수동 설정",
	"AFTR IPv6 Address": "AFTR IPv6 주소",
	"B4 IPv4 Address": "B4 IPv4 주소",
	"WAN IPv6 Address": "WAN IPv6 주소",
	"IPv6 WAN Default Gateway": "IPv6 기본 게이트웨이",
	"Advanced Settings": "고급 설정",
	"Manual": "수동 설정",
	"Always on": "항상 켜짐",
	"On demand": "필요 시 연결",
	"Dynamic IP": "유동 IP",
	"The MTU value should be 1280 ~ 1460.": "1280 ~ 1460 사이의 값으로 설정하여 주십시오.",
	"The MTU value should be 1280 ~ 1492.": "1280 ~ 1492 사이의 값으로 설정하여 주십시오.",
	"The MTU value should be 1280 ~ 1500.": "1280 ~ 1500 사이의 값으로 설정하여 주십시오.",
	"IPv6 PPPoE is share with IPv4 PPPoE. Please change IPv6 WAN protocol to PPPoE at first.": "IPv6 PPPoE 방식은 IPv4 PPPoE 방식과 연동되어 있습니다. 먼저 IPv6 연결 방식을 PPPoE로 변경하여 주십시오.",
	"Please choose one IPv6 connection type besides Link-Local Only, 6to4, 6rd, and IPv6 in IPv4 Tunnel !": "IPv6 연결 방식에는 Link-Local, 6to4, 6rd, IPv6-IPv4 터널이 있습니다. 사용하고 있는 IPv6 서비스를 확인하여 선택하여 주십시오.",
	"The default gateway should be in the same network.": "기본 게이트웨이 주소가 동일 네트워크 상의 주소로 입력되어야 합니다.",
	"The dns server cannot be equal to the IP address.": "DNS 주소는 IP 주소와 다르게 입력하여 주십시오.",
	"The router would not support the subnet mask which length is less than Class A.": "공유기는 클래스 A보다 작은 서브넷 마스크는 지원하지 않습니다.",
	"Please enter a primary dns server": "기본 DNS 서버 주소를 입력하여 주십시오.",
	"Secondary DNS server should not be the same as Primary DNS server.": "보조 DNS 서버는 기본 DNS 서버와 다르게 설정 하십시오.",
	"The network id is the same with LAN.": "네트워크 ID는 LAN과 동일 합니다.",


	"All of your IPv6 Internet and network connection details are displayed on this page.": "IPv6 인터넷 및 네트워크 연결의 자세한 내용은 모두 이 페이지에 표시됩니다.",
	"Auto Detection": "자동 감지",
	"Static IPv6": "고정 IPv6",
	"Auto Configuration (SLAAC/DHCPv6)": "자동 구성(SLAAC/DHCPv6)",
	"IPv6 in IPv4 Tunnel": "IPv6 over IPv4 Tunnel",
	"6to4": "6to4",
	"Local Connectivity Only": "로컬 연결만 전용",
	"Use Link-Local Address": "Link-Local 주소 사용",
	"Subnet Prefix Length": "서브넷 Prefix 길이",
	"PPPoE Session": "PPPoE 세션",
	"Remote IPv4 Address": "원격 IPv4 주소",
	"Remote IPv6 Address": "원격 IPv6 주소",
	"Local IPv4 Address": "로컬 IPv4 주소",
	"Local IPv6 Address": "로컬 IPv6 주소",
	"6to4 Address": "6to4 주소",
	"6to4 Relay": "6to4 릴레이",
	"Assign IPv6 Prefix": "IPv6 Prefix 할당",
	"LAN IPv6 Link-Local Address": "LAN IPv6 Link-Local 주소",
	"IPv6 DNS SETTINGS": "IPv6 DNS 설정",
	"LAN IPv6 ADDRESS SETTINGS": "LAN IPv6 주소 설정",
	"LAN IPv6 Address": "LAN IPv6 주소",
	"ADDRESS AUTOCONFIGURATION SETTINGS": "주소 자동 설정",
	"Enable Automatic IPv6 Address Assignment": "IPv6 주소 자동 할당 사용",
	"Enable Automatic DHCP-PD in LAN": "LAN 자동 DHCP-PD 사용",
	"Autoconfiguration Type": "자동 유형",
	"Enable DHCP-PD": "DHCP-PD 사용",
	"6RD MANUAL CONFIGURATION": "6rd 수동 구성",
	"Enable Hub and Spoke Mode": "Hub&Spoke 모드 사용",
	"6rd Configuration": "6RD 구성",
	"6rd IPv6 Prefix": "6rd IPv6 Prefix",
	"6rd Border Relay IPv4 Address": "6rd Border Relay IPv4 주소",
	"IPv6 ULA SETTINGS": "IPv6 ULA 설정",
	"Enable ULA": "ULA 사용",
	"Use Default ULA Prefix": "기본 ULA Prefix 사용",
	"ULA Prefix": "ULA Prefix",
	"CURRENT IPv6 ULA SETTINGS": "현재 IPv6 ULA 설정",
	"Current ULA Prefix": "현재 ULA Prefix",
	"LAN IPv6 ULA": "LAN IPv6 ULA",
	"minutes": "분",
	"DNS Type": "DNS 유형",
	"Obtain a DNS server address automatically": "자동 DNS 서버 주소 받기",
	"Use the following DNS address": "다음 DNS 주소 사용",
	"SLAAC+Stateless DHCP": "SLAAC+Stateless DHCP",
	"Stateful DHCPv6": "Stateful DHCPv6",
	"6rd DHCPv4 Option": "6RD DHCPv4 옵션",
	"Share with IPv4": "IPv4 공유",
	"Create a new session": "새로운 세션 생성",
	"bytes": "바이트",
	"Router Advertisement Lifetime": "공유기 알림 주기",
	"IPv6 Address Range (Start)": "IPv6 주소 범위(시작)",
	"IPv6 Address Range (End)": "IPv6 주소 범위(마지막)",
	"IPv6 Address Lifetime": "IPv6 주소 유지시간",
	"WAN IPv4 Address": "IPv4 인터넷 주소",


	"coexistence": "HT20/40 공생",
	"Security Mode": "보안 모드",
	"None": "없음",
	"WPA/WPA2-Personal": "WPA/WPA2-Personal",
	"Auto": "자동",
	"High": "높음",
	"Low": "낮음",
	"802.11 Mode": "802.11 모드",
	"Wi-Fi Channel": "Wi-Fi 채널",
	"Transmission Power": "전송 전력",
	"Channel Width": "채널 폭",
	"Visibility Status": "무선 숨김 기능",
	"Visible": "무선 숨기지 않음",
	"Invisible": "무선 숨김",
	"Mixed 802.11b/g": "802.11b/g 혼용",
	"Mixed 802.11g/n": "802.11g/n 혼용",
	"Mixed 802.11b/g/n": "802.11b/g/n 혼용",
	"Auto 20/40 MHz": "자동 20/40 MHz",
	"Auto 20/40/80 MHz": "자동 20/40/80 MHz",
	"Use this section to configure the wireless settings for your D-Link Router. Please note that changes made on this section may also need to be duplicated on your Wireless Client.": "이곳에서 D-Link 공유기의 무선 설정을 구성할 수 있습니다. 변경한 설정에 따라 무선 클라이언트를 다시 연결해야 합니다.",
	"This page lets you configure a Wi-Fi Guest Zone. Wi-Fi Guest Zones are Wi-Fi networks that are separate from your normal ones, and use different Wi-Fi Network Names and passwords. Users connected to a Guest Zone cannot communicate or detect devices on your normal network unless the Routing Between Zones option is enabled. Guest Zones are useful to give guests Internet access without allowing them to access your own devices on your network.": "이 메뉴에서 Wi-Fi 인터넷 게스트 존을 활성화 할 수 있습니다. 게스트존에 인터넷 접속전용 옵션이 활성화 되어 있다면 연결된 사용자는 홈 네트워크의 내부장치를 검색 할 수 없습니다.",
	"Internet Access Only": "내부 네트워크 연결 차단",
	"Home Network Access": "홈 네트워크 접속",
	"Your changes are being saved. When reconnecting to this device, please use the new Wi-Fi name and password you created.": "설정을 저장하고 있습니다. 이 장치에 다시 연결하려면, 새로운 Wi-Fi 이름과 비밀번호를 사용 하십시오.",
	"Your changes are being saved.": "설정을 저장하고 있습니다.",
	"Mixed 802.11a/n": "802.11a/n 혼용",
	"Mixed 802.11n/ac": "802.11n/ac 혼용",
	"Mixed 802.11a/n/ac": "802.11a/n/ac 혼용",
	"802.11b only": "802.11b 만",
	"802.11g only": "802.11g 만",
	"802.11n only": "802.11n 만",
	"802.11a only": "802.11a 만",
	"802.11ac only": "802.11ac 만",
	"Please select a wireless station.": "무선 단말을 선택하여 주십시오.",
	"Station": "단말",
	"Wireless Network Name": "무선 네트워크 이름",
	"Security": "보안",
	"Scan": "검색",
	"Password Length": "비밀번호 길이",
	"WI-FI PROTECTED SETUP": "Wi-FI Protected 설정(WPS)",
	"WPS status": "WPS 상태",
	"Device PIN": "PIN 코드",
	"Generate New PIN": "PIN 코드 생성",
	"Save Device PIN": "PIN 코드 저장",
	"Reset to Unconfigured": "설정하지 않은 상태로 리셋",
	"PBC": "PBC",
	"PBC Start": "PBC 연결 시작",
	"PIN": "PIN",
	"PIN Start": "PIN 코드 연결 시작",
	"Scanning...": "검색 중...",
	"Available hotspot networks": "사용할 수 있는 핫스팟 네트워크",
	"WPA-Personal": "WPA-Personal",
	"Select": "선택",
	"WEP password length is 10 or 26, password type must be Hexadecimal.": "WEP 비밀번호를 HEX값으로 설정하는 경우 10자리 혹은 26자리의 16진수로 입력해야 합니다.",
	"Your password must be 5 or 10 or 13 or 26 length.": "HEX 값 설정 시 10자리 또는 26자리의 16진수 입력하여 주십시오. <br>ASCII 값 설정 시 5자리 또는 13자리로 입력하여 주십시오.",
	"WPA password length is 64, password type must be Hexadecimal.": "WPA 비밀번호를 64자리 설정 시 16진수로 입력해야 합니다.",


	"Network": "네트워크",
	"Network Settings": "네트워크 설정",
	"DHCP Server": "DHCP 서버",
	"LAN IP Address": "LAN IP 주소",
	"Device Name": "장치명",
	"Local Domain Name": "로컬 도메인 이름",
	"Enable DNS Relay": "DNS 릴레이 사용",
	"DHCP IP Address Range": "DHCP IP 주소 범위",
	"DHCP Lease Time": "DHCP 임대 시간",
	"Always Broadcast": "항상 Broadcast",
	"compatibility for some DHCP Clients": "일부 DHCP 클라이언트와 호환하기 위해 사용",
	"If you changed the IP address of the router you will need to change the IP address in your browser before accessing the configuration website again.": "공유기의 LAN IP 주소를 변경 한 경우 공유기 설정 화면에 다시 접속하기 위해서 브라우저에 변경된 LAN IP 주소를 입력해야 합니다.",
	"The new settings have been saved.": "새로운 설정이 저장되었습니다.",
	"to": "부터",
	"Management Link": "관리 링크",


	"Advanced Network": "고급 네트워크",
	"Advanced Network settings allow you to configure some of the more advanced features of your router. It is recommended that you only change these settings if you are  familiar with them, or if you are specifically instructed to do so.": "고급 네트워크 설정은 공유기의 고급 기능을 설정 할 수 있습니다. 고급 기능에 대하여 익숙하거나 반드시 필요한 경우에만 변경하시기 바랍니다.",
	"UPnP": "UPnP",
	"WAN Port Speed": "WAN 포트 속도",
	"IPv4 Multicast Streams": "IPv4 멀티 캐스트 스트림",
	"IPv6 Multicast Streams": "IPv6 멀티 캐스트 스트림",
	"Auto (10/100/1000 Mbps)": "자동 (10/100/1000 Mbps)",


	"SharePort allows you to share photos, music, movies and files simply by connecting a USB drive to your router. Access your files locally and remotely using the free mydlink SharePort app for your iOS or Android devices, or access them on a computer through the SharePort Web Access. The built-in Digital Living Network Alliance (DLNA) media server allows you to stream multimedia content to any DLNA compliant devices such as smart TVs and games consoles.": "SharePort는 공유기에 장착한 USB 저장장치에 보관된 사진, 음악, 동영상, 파일을 공유하는 기능입니다. 스마트폰에서 mydlink SharePort 앱을 이용하여 로컬 및 원격으로 접속하실 수 있으며, PC 에서는 웹브라우저를 이용하여 쉽게 접속하실 수 있습니다. DLNA 미디어 서버는 DLNA 를 지원하는 스마트TV 및 게임콘솔에서 멀티미디어 파일을 실시간으로 재생할 수 있도록 하는 기능입니다.",
	"DLNA Media Server Configuration": "DLNA 미디어 서버 설정",
	"DLNA Media Server": "DLNA 미디어 서버",
	"Web File Access": "웹 파일 접속",
	"Remote Access Port": "원격 접속 포트",
	"Remote HTTPS Port": "원격 HTTPS 포트",
	"Enable Storage Remote Access": "스토리지 원격 접속 사용",
	"Direct Links": "직접 링크",
	"Local Access": "로컬 액세스",
	"SharePort Web Access": "SharePort 웹 접속",
	"Windows File Sharing (SAMBA)": "윈도우 파일 공유(SAMBA)",
	"Windows File Sharing": "윈도우 파일 공유",
	"Require router's admin password": "공유기 관리자 비밀번호로 접속",
	"Allow all users to access (No password)": "모든 사용자 접속 허용(비밀번호 없음)",


	"\"Create User\" manage access to your storage devices or use the Guest account (guest/guest) to access the Guest Folder. After plugging in an SD card or USB storage drive, the new device will appear in the list with a link to it. You can then use this link to connect the drive and login with a user account.": "\"사용자 만들기 \"에서 저장 장치에 대한 접속을 관리할 수 있으며 게스트 폴더에 접속하려면 게스트 계정 (guest/guest)를 사용 할 수도 있습니다. SD 카드나 USB 저장 드라이브를 연결하면 새 장치에 대한 링크와  목록이 나타납니다. 링크를 통해 드라이브에 접속하고 사용자 계정으로 로그인 할 수 있습니다.",
	"Remote Access": "원격 접속",
	"Create User": "사용자 만들기",
	"User Name": "사용자 이름",
	"Access Path": "접속 경로",
	"Permission": "허가",
	"Edit": "수정",
	"Delete": "삭제",
	"Browse": "찾아보기",
	"Apply": "적용",
	"Create User": "사용자 만들기",
	"Create New User": "새로운 사용자 만들기",
	"Edit User Profile": "사용자 프로필 편집",
	"Folder": "폴더",
	"Select Folder": "폴더 선택",
	"USB Device Name": "USB 장치명",
	"Number of Device": "장치 수",
	"Read/Write": "읽기/쓰기",
	"Read Only": "읽기 전용",
	"root": "root",
	"USB Port": "USB 포트",
	"Disk Name": "드라이브 이름",


	"Creating a mydlink account and registering your router with mydlink will allow you to remotely montior and manage your network on your smartphone or tablet, as well as through the secure web portal. It also allows you to plug in a USB drive and access the stored files from anywhere in the world through iOS and Android apps as well as the web browser on your computer.": "공유기를 mydlink 서비스에 등록하면, mydlink 포털 웹사이트 및 스마트 기기용 mydlink 어플리케이션을 통해 온라인으로 공유기 관리가 가능한 mydlink 클라우드 서비스 기능을 사용 할 수 있습니다.",
	"mydlink Registration": "mydlink 등록 완료",
	"Sign Up": "가입하기",
	"Sign In": "로그인",
	"Please enter your e-mail address and mydlink password.": "이메일 주소와 mydlink 비밀번호를 입력하여 주십시오.",
	"You must accept the terms and conditions to continue.": "계속 진행하시려면, 본 사용권 및 조건에 동의하여 주십시오.",
	"mydlink Account": "mydlink 계정",
	"mydlink Service": "mydlink 서비스",


	"QoS Engine": "QoS 엔진",
	"Connected clients can be assigned Internet access priority. Click and drag client cards into open slots.": "연결 된 클라이언트의 인터넷 접속 우선 순위를 할당 할 수 있습니다. 클라이언트 카드를 드래그하여 슬롯에 넣어주세요.",
	"Drag the device cards above to the Priority boxes below.": "아래의 Priority 상자에 위의 장치 카드를 드래그합니다.",
	"Highest": "가장 높음",
	"Medium": "중간",


	"Firewall": "방화벽",
	"Your router's high-performance firewall feature continuously monitors Internet traffic, protecting your network and connected devices from malicious Internet attacks.": "공유기의 고성능 방화벽은 지속적으로 인터넷 트래픽을 모니터링하여, <br>인터넷 공격으로부터 네트워크와 연결된 클라이언트를 보호합니다.",
	"Application Level Gateway (ALG) Configuration": "어플리케이션 레벨 게이트웨이 (ALG) 설정",
	"Enable SPI IPv4": "SPI IPv4 사용",
	"Enable Anti-spoof Checking": "Anti-spoof 검사 사용",
	"IPv6 Simple Security": "IPv6 단순 보안",
	"IPv6 Ingress Filtering": "IPv6 인그레스 필터링 활성화",
	"PPTP": "PPTP",
	"IPSec (VPN)": "IPSec (VPN)",
	"RTSP": "RTSP",
	"SIP": "SIP",
	"IPv4 Rules": "IPv4 규칙",
	"IPv6 Rules": "IPv6 규칙",
	"Enable DMZ Host": "DMZ 호스트 사용",
	"DMZ IP Address": "DMZ IP 주소",


	"The IPv4 rule section is an advance feature used to deny or allow traffic from passing through the device.": "이곳에서는 장치를 통과하는 트래픽의 차단 또는 허용하는 IPv4 규칙을 설정 할 수 있습니다.",
	"Your router's built-in firewall also supports IPv6. Some applications or clients may require special adjustment for better performance or extra protection.": "공유기의 방화벽은 IPv6를 지원합니다.일부 어플리케이션이나 클라이언트는 성능 향상이나 추가 보호를 위해 특별한 설정이 필요합니다.",
	"Any": "모두",
	"Add Rule": "규칙 추가",
	"Name": "이름",
	"Schedule": "스케줄",
	"Source IP Address Range": "출발지 IP 주소 범위",
	"Destination IP Address Range": "목적지 IP 주소 범위",
	"Port Range": "포트 범위",
	"Turn IPv4 Filtering OFF": "IPv4 필터링 끄기",
	"Turn IPv4 Filtering ON and ALLOW rules listed": "IPv4 필터링을 켜고 규칙 리스트 허용",
	"Turn IPv4 Filtering ON and DENY rules listed": "IPv4 필터링을 켜고 규칙 리스트 차단",
	"Turn IPv6 Filtering OFF": "IPv6 필터링 끄기",
	"Turn IPv6 Filtering ON and ALLOW rules listed": "IPv6 필터링을 켜고 규칙 리스트 허용",
	"Turn IPv6 Filtering ON and DENY rules listed": "IPv6 필터링을 켜고 규칙 리스트 차단",
	"Create New Rule": "새 규칙 만들기",
	"Create New Route": "새로운 경로 만들기",
	"Edit Rule": "규칙 수정",
	"Edit Route": "경로 수정",


	"Your router helps share a single IP address assigned by your ISP among several clients in your home. Port forwarding allows traffic requests from a specified application to be directed to a specified client inside.": "포트 포워딩은 공유기에서 포트를 열고 해당 포트에 대한 트래픽을 네트워크에 있는 특정 장치로 전달하는 기능으로 특정 어플리케이션, 게임, 서비스 사용 시 필요할 수 있습니다. 포트 번호는 개별 포트(80, 68, 888), 범위 포트(100-150), 개별 포트와 범위 포트가 혼합된 형식(1020-5000, 689)으로 입력할 수 있습니다.",
	"Local IP": "로컬 IP",
	"TCP Port": "TCP 포트",
	"UDP Port": "UDP 포트",


	"Your router helps share a single IP address assigned by your Internet service provider among several clients in your home. Virtual servers are preset port mappings for popular services, like a web or e-mail server, that route traffic to a specified client inside.": "공유기는 인터넷 공급 업체(ISP)에서 할당받은 하나의 IP 주소를 여러 클라이언트가 공유하여 사용할 수 있도록 합니다. 가상 서버 설정은 웹 서버, 이메일 서버 등 많이 사용하는 서비스의 포트를 미리 설정하여 내부에 있는 특정 클라이언트에 트래픽을 전달 할 수 있도록 합니다.",
	"Protocol": "프로토콜",
	"External Port": "외부 포트",
	"Internal Port": "내부 포트",
	"Protocol Number": "프로토콜 번호",
	"Both": "둘다",
	"Other": "기타",


	"The website filters feature allows rules to be set that restrict access to a specified web address (URL) or blocks specified keywords in the URL. You can use Website Filter to restrict access to potentially harmful and inappropriate websites.": "웹 사이트 필터 기능은 특정 웹 주소나 특정 키워드가 포함된 웹 주소 대한 접속을 허용하거나 차단 할 수 있습니다. 유해하거나 부적절한 웹 사이트 접속을 차단하기 위해 웹 사이트 필터 기능을 사용하실 수 있습니다.",
	"DENY clients access to ONLY these sites": "이 사이트만 접속 차단",
	"ALLOW clients access to ONLY these sites": "이 사이트만 접속 허용",
	"Website URL/Domain": "웹 사이트 URL / 도메인",


	"Static Routes": "고정 경로",
	"Once connected to the Internet, your router automatically builds routing tables that determine where traffic should be sent. Static routes can override this process, allowing traffic to be directed to a specific client or location.": "공유기가 인터넷에 한 번 연결된 경우, 트래픽을 어디로 전송해야 하는지 결정하는 라우팅 테이블이 자동으로 생성됩니다. 고정 경로 설정은 라우팅 테이블을 수동으로 설정하여 트래픽을 특정 클라이언트나 위치로 바로 전송 할 수 있도록 합니다.",
	"Destination Network": "목적지 네트워크",
	"Mask": "마스크",
	"Gateway": "게이트웨이",
	"Metric": "경로 설정 값",
	"Interface": "인터페이스",
	"DestNetwork": "목적지 네트워크",
	"PrefixLen": "Prefix 길이",
	"Add Route": "경로 추가",
	"This page allows you to define custom routes to define how data traffic is moved around your network": "이 페이지에서 테이터 트래픽의 네트워크 이동 경로를 정의할 수 있습니다.",


	"Dynamic Domain Name Service allows your router to associate an easy-to-remember domain name such as [YourDomainName].com with the regularly changing IP address assigned by your Internet Service provider. This feature is helpful when running a virtual server.": "Dynamic DNS 설정은 인터넷 공급 업체(ISP)로부터 할당 받은 유동 IP 주소를 [도메인 이름].COM과 같이 기억하기 쉬운 이름과 연결시켜 주는 기능입니다. 이 기능은 가상 서버를 사용할 때 유용합니다.",
	"Server Address": "서버 주소",
	"Dynamic DNS": "DDNS",
	"Enable Dynamic DNS": "DDNS 사용",
	"Select Server Name": "서버 이름 선택",
	"Time Out": "시간 만료",
	"IPv6 Address": "IPv6 주소",
	"hours": "시간",
	"Add Record": "이력 추가",
	"Create New Record": "새로운 이력 만들기",
	"Edit Record": "이력 수정",


	"Time & Schedule": "시간 및 스케줄",
	"Time": "시간",
	"Time Configuration": "시간 설정",
	"Automatic Time Configuration": "자동 시간 설정",
	"Manual Time Configuration": "수동 시간 설정",
	"Date": "날짜",
	"Your router's internal clock is used for data logging and schedules for features. The date and time can be synchronized with a public time server on the Internet, or set manually.": "이곳에서 로그 및 스케줄에 사용할 공유기의 시스템 시간을 설정할 수 있습니다. 시스템 시간은 인터넷 상의 시간 서버와 자동으로 동기화 하거나 수동으로 설정 할 수 있습니다.",
	"System Time": "시스템 시간",
	"Time Zone": "표준 시간대",
	"Enable Daylight Saving": "일광 절약 사용",
	"Update Time Using an NTP Server": "NTP 서버 동기화 사용함",
	"Year/ Month/ Day": "년/ 월/ 일",
	"Hour/ Minute": "시/ 분",
	"Day": "일",
	"Hour": "시",
	"Min": "분",
	"Sec": "초",
	"D-Link NTP Server": "D-Link NTP 서버",
	"NTP Server": "NTP 서버",


	"Some features, such as the firewall and website filters, can be turned on or off based on a schedule. One common use of schedules is to control access to the Internet by a specified device during specified time periods.": "웹사이트 필터나 방화벽 같은 일부 기능들은 스케줄에 따라 켜거나 끌 수 있습니다. 일반적으로 특정 단말에 대해 정해진 시간 동안에 인터넷 접속을 제어하는데 사용됩니다.",
	"Monday": "월요일",
	"Tuesday": "화요일",
	"Wednesday": "수요일",
	"Thursday": "목요일",
	"Friday": "금요일",
	"Saturday": "토요일",
	"Sunday": "일요일",
	"All Day": "하루 종일",
	"All Week": "매주",
	"Always": "계속 사용함",
	"Name": "이름",
	"Schedule cannot be null!": "스케줄을 입력하여 주십시오!",


	"System Log": "시스템 로그",
	"SysLog Settings": "시스템 로그 설정",
	"On-board diagnostics run continually in the background to monitor the health of your router. The results are recorded in the system log if it is enabled. This info can be used to diagnose common problems or help Customer Support resolve issues more quickly.": "공유기의 백그라운드에는 상태를 모니터링하기 위해 진단 장치가 지속적으로 동작합니다. 이 기능을 사용하면 시스템 로그에 기록이 남게 됩니다. 로그 정보는 공유기의 문제를 진단하거나 빠른 고객 지원에 도움이 될 수 있습니다.",
	"SysLog Server IP Address": "Syslog 서버 IP 주소",
	"Enable Logging to Syslog Server": "Syslog 서버 사용",
	"E-mail Settings": "이메일 설정",
	"E-mail Log When Full or On Schedule": "이메일 로그 알림 설정",
	"Enable E-mail Notification": "이메일 알림 사용",
	"From E-mail Address": "보내는 이메일 주소",
	"To E-mail Address": "받는 이메일 주소",
	"SMTP Server Address": "SMTP 서버 주소",
	"SMTP Server Port": "SMTP 서버 포트",
	"Enable Authentication": "인증 사용",
	"Account Name": "계정 이름",
	"Send When Log Full": "Log-Full 전송",
	"Send on Schedule": "스케줄 적용하여 발송",


	"System": "시스템",
	"Save Configuration": "설정 저장",
	"Restore Configuration From File": "파일에서 설정 복구",
	"Restore Factory Default": "공장 초기화",
	"Reboot": "재부팅",
	"This page lets you save your router's current settings to a file, restore your settings from a file, restore your router to factory default settings, or reboot the device. Please note that restoring the settings to the factory defaults will erase all settings, including any rules you have created.": "이곳에서 공유기의 현재 설정을 저장하거나 복구할 수 있고 공장 초기화 및 재부팅을 할 수 있습니다. 공유기를 초기화하면 사용자가 만든 모든 설정과 규칙이 삭제됩니다.",
	"Save Settings To Local Hard Drive": "로컬 드라이브에 설정 저장",
	"Load Settings From Local Hard Drive": "로컬 드라이브에서 설정 불러오기",
	"Restore To Factory Default Settings": "공장 초기화",
	"Reboot The Device": "장치 재부팅",
	"Cancel": "취소",
	"Are you sure you want to restore configuration file?": "설정 파일을 복구 하시겠습니까?",
	"Do not close the page or power off the service until the restore configuration file is complete!": "설정 파일 복구가 끝날 때 까지 전원을 끄거나 페이지를 닫지 마십시오.",
	"Restore configuration file failed!": "설정 파일 복구가 실패 하였습니다!",
	"Restore configuration file success!": "설정 파일 복구가 실패 하였습니다!",
	"Rebooting": "재부팅 중",
	"Reboot success!": "재부팅이 완료되었습니다!",
	"Are you sure you want to reset the device to its factory default settings? This will cause current settings to be lost.": "장치를 공장 초기화 하시겠습니까? 현재 설정이 삭제 될 수 있습니다.",
	"Restore to factory default success!": "공장 초기화 완료",
	"Select File": "파일 선택",
	"Restore": "복구",
	"Are you sure you want to restart the device?": "장치를 재시작 하시겠습니까?",
	"OK": "진행",


	"Admin": "관리자",
	"Admin Password": "관리자 비밀번호",
	"Administration": "관리",
	"Use HTTPS": "HTTPS 사용",
	"The admin account can change all router settings. To keep your router secure, you should give the admin account a strong password.": "admin 계정은 공유기의 모든 설정을 변경 할 수 있습니다. 공유기의 보안을 위해 비밀번호를 설정하시기 바랍니다.",
	"Enable Graphical Authentication (CAPTCHA)": "그래픽 인증 사용(CAPTCHA)",
	"Enable HTTPS Server": "HTTPS 서버 사용",
	"Enable Remote Management": "원격 관리 설정",
	"Remote Admin Port": "원격 관리 포트",
	"Remote Admin Inbound Filter": "원격 관리 인바운드 필터",


	"Upgrade Firmware": "펌웨어 업그레이드",
	"Your router can automatically detect firmware updates, but requires your authorization to install them. It is also possible to check for new firmware manually, upgrade firmware from a local file.": "공유기의 최신 펌웨어는 자동으로 확인이 가능하지만 설치는 관리자의 동의가 필요합니다. 수동으로 업그레이드 하는 경우 mydlink.co.kr에서 다운로드 받아서 진행 할 수 있습니다.",
	"Current Firmware Version": "현재 펌웨어 버전",
	"Current Firmware Date": "현재 펌웨어 날짜",
	"Current Language Pack": "현재 언어 팩",
	"Download New Firmware": "최신 펌웨어 다운로드",
	"Add a Language Pack": "언어팩 추가",
	"Upload": "업로드",
	"Upgrade": "업그레이드",
	"Do you want to upgrade Firmware?": "펌웨어를 업그레이드 하시겠습니까?",
	"Do not power off the device until the Firmware Upgrade is complete!": "펌웨어 업그레이드가 완료 될 때까지 장치의 전원을 끄지 마십시오.",
	"Uploading Firmware": "펌웨어 업로드 중",
	"Firmware Upgrade failed!": "펌웨어 업그레이드에 실패하였습니다.",
	"Firmware Upgrade success!": "펌웨어 업그레이드가 완료되었습니다.",
	"Firmware Information": "펌웨어 정보",
	"New Firmware Version": "새로운 펌웨어 버전",
	"New Firmware Date": "최신 펌웨어 날짜",
	"Check for New Firmware": "최신 펌웨어 확인",
	"Language Pack Information": "언어 팩 정보",
	"Remove": "제거",
	"Upgrade Manually": "수동 업그레이드",
	"Checking": "확인 중입니다.",
	"Retry": "재시도",
	"This firmware is the latest version.": "최신 펌웨어로 업그레이드 되어 있습니다.",
	"Downloading": "다운로드 중",
	"Please do not close the browser while the firmware is being downloaded!": "펌웨어 다운로드 중에는 페이지를 닫지 마십시오!",
	"Upgrading": "업그레이드 중",


	"Statistics": "통계",
	"This page gives you various statistics about data transmitted and received by your router through the Internet, on your wired network (LAN), and through your wireless networks.": "이곳에서는 공유기를 통한 유,무선 단말의 인터넷 사용량에 대한 통계를 볼 수 있습니다.",
	"Clear": "클리어",
	"Information: Your browser is not support HTML5, please upgrade your browser.": "정보 : 브라우저가 HTML5를 지원하지 않습니다, 브라우저를 업그레이드 하시기 바랍니다.",
	"Sent (Tx)": "전송 (TX)",
	"Received (Rx)": "수신 (RX)",
	"Total Packets": "총 패킷",
	"Total KByte(s)": "총 KBytes(s)",
	"KByte/sec": "Kbits/sec",
	"Session": "세션",

	"Router Not Found": "공유기를 감지할 수 없습니다.",
	"Please enter an IP address.": "IP 주소를 입력하여 주십시오.",
	"Please enter an e-mail address.": "이메일 주소를 입력하여 주십시오.",
	"Please enter your e-mail account name.": "이메일 계정 이름을 입력하여 주십시오.",
	"Please enter your e-mail password.": "이메일 비밀번호를 입력하여 주십시오.",
	"Please enter a Wi-Fi Name(SSID).": "Wi-Fi 이름(SSID)을 입력하여 주십시오.",
	"Please enter a subnet mask.": "서브넷 마스크를 입력하여 주십시오.",
	"Please enter a device name.": "장치명을 입력하여 주십시오.",
	"Please enter a name for your DLNA Media Server.": "DLNA 미디어 서버 이름을 입력하여 주십시오.",
	"Please enter a port number.": "포트 번호를 입력하여 주십시오.",
	"Please enter a name for this rule.": "규칙 이름을 입력하여 주십시오.",
	"Please enter an IP address range.": "IP 주소 범위를 입력하여 주십시오.",
	"Please enter a port range.": "포트 범위를 입력하여 주십시오.",
	"Please enter a valid IP address range. (e.g. 1.1.1.1-1.1.1.2)": "유효한 IP 주소 범위를 입력하여 주십시오. (예 : 1.1.1.1-1.1.1.2)",
	"Please enter a valid port range. (e.g. 1000-1001)": "유효한 포트 범위를 입력하여 주십시오. (예 : 1000-1001)",
	"Please enter a valid port number.": "유효한 포트 번호를 입력하여 주십시오.",
	"Please enter a netmask.": "서브넷 마스크를 입력하여 주십시오.",
	"Please enter a gateway address.": "게이트웨이 주소를 입력하여 주십시오.",
	"Please enter a Metric.": "경로 설정 값을 입력하여 주십시오.",
	"Please enter a valid netmask. (e.g. 255.255.255.0)": "유효한 넷 마스크를 입력하여 주십시오. (예 : 255.255.255.0)",
	"Please enter a valid gateway address. (e.g. 192.168.0.1)": "유효한 게이트웨이 주소를 입력하여 주십시오. (예 : 192.168.0.1)",
	"Please enter a destination network IP address.": "목적지 IP 주소를 입력하여 주십시오.",
	"Please enter a prefix length.": "prefix 길이를 입력하여 주십시오.",
	"Please enter a valid IPv6 address. (e.g. 2001::1)": "유효한 IPv6 주소를 입력하여 주십시오. (예 : 2001 :: 1)",
	"Please enter a valid destination network IP address. (e.g. 2001::)": "유효한 목적지 네트워크의 IP 주소를 입력하여 주십시오. (예 : 2001::)",
	"Please enter an SMTP server address.": "SMTP 서버 주소를 입력하여 주십시오.",
	"Please enter a valid IP address. (e.g. 192.168.0.1)": "유효한 IP 주소를 입력하여 주십시오. (예 : 192.168.0.1)",
	"Please enter a valid IP address. (e.g. 255.255.255.0)": "유효한 IP 주소를 입력하여 주십시오. (예 : 255.255.255.0)",
	"Please enter a username.": "사용자 이름을 입력하여 주시기 바랍니다..",
	"Please enter a password.": "비밀번호를 입력하여 주십시오.",
	"Please enter a valid e-mail.": "이메일 주소를 입력하여 주십시오.",
	"Please enter a host name.": "호스트 이름을 입력하여 주십시오.",
	"Please enter a source network IP address.": "출발지 네트워크 IP 주소를 입력하여 주십시오.",
	"Please enter a valid IPv6 address range (e.g., 2001::1-2001::2)": "IPv6 주소 범위를 입력하여 주십시오. (예, 2001::1-2001::2)",
	"Your password must be 13 characters length": "비밀번호를 13 자리로 입력하여 주십시오.",
	"Your password must be between 8-63 characters length": "비밀번호를 8 ~ 63 자리로 입력하여 주십시오.",
	"Your password must be between 6-15 characters length": "비밀번호를 6 ~ 15 자리로 입력하여 주십시오.",
	"Text field contains illegal characters.": "잘못된 문자가 포함되어 있습니다.",
	"Please enter a value between 0 and FF": "16진수로 입력하여 주십시오. (0~9/A~F/a~f)",
	"End range must be greater than the start range": "마지막 IP 주소가 시작 IP 주소보다 커야 합니다.",
	"Please enter a value": "해당 값을 입력하여 주십시오.",
	"Please enter an IPv6 address.": "IPv6 주소를 입력하여 주십시오.",
	"IPv4 Connection Type must to be PPPoE Session": "IPv4 연결 방식이 PPPoE로 설정되어 있어야 합니다.",
	"You should choose another IPv4 Internet Connection mode rather than 'DS-Lite' to access the Internet.": "인터넷 연결을 위해 'DS-Lite'가 아닌 다른 IPv4 인터넷 연결 모드를 선택하여 주십시오.",


	"err_required": "IP 주소를 입력하십시오.",
	"err_email": "전자 메일 주소를 입력 해주십시오.",
	"err_email_AccountName": "전자 메일 계정 이름을 입력 해주세요.",
	"err_email_Password": "전자 메일 암호를 입력하십시오.",
	"err_ssid": "와이파이 이름 (SSID)을 입력하십시오.",
	"err_ip": "IP 주소를 입력하십시오.",
	"err_subnet_Mask": "서브넷 마스크를 입력하십시오.",
	"err_device_Name": "장치 이름을 입력하십시오.",
	"err_dlna_Name": "귀하의 DLNA 미디어 서버의 이름을 입력하십시오.",
	"err_port": "포트 번호를 입력하십시오.",
	"err_rule_Name": "이 규칙에 대한 이름을 입력 해주세요.",
	"err_ip_Range": "IP 주소 범위를 입력하십시오.",
	"err_port_Range": "포트 범위를 입력하십시오.",
	"err_address_CheckRange": "유효한 IP 주소 범위를 입력하십시오. (예 : 1.1.1.1-1.1.1.2)",
	"err_port_CheckRange": "유효한 포트 범위를 입력하십시오. (예 : 1000-1001)",
	"err_port_Check": "유효한 포트 번호를 입력하십시오.",
	"err_netmask": "넷 마스크를 입력하십시오.",
	"err_gateway_Address": "게이트웨이 주소를 입력 해주십시오.",
	"err_matrix": "행렬을 입력하십시오.",
	"err_netmask_Check": "유효한 넷 마스크를 입력하십시오. (예 : 255.255.255.0)",
	"err_gateway_AddressCheck": "유효한 게이트웨이 주소를 입력 해주십시오. (예 : 192.168.0.1)",
	"err_destinationIP": "대상 네트워크 IP 주소를 입력하십시오.",
	"err_prefix_Length": "접두사 길이를 입력하십시오.",
	"err_ipv6address_Check": "유효한 IPv6의 주소를 입력 해주십시오. (예 : 2001 :: 1)",
	"err_ipv6networkaddress_Check": "유효한 대상 네트워크의 IP 주소를 입력하십시오. (예 : 2001::)",
	"err_smtp": "SMTP 서버 주소를 입력 해주십시오.",
	"err_address_Check": "유효한 IP 주소를 입력 해주십시오. (예 : 192.168.0.1)",
	"err_address_CheckAllRange": "유효한 IP 주소를 입력 해주십시오. (예 : 255.255.255.0)",
	"err_check_UserName": "이름을 입력하세요.",
	"err_check_Password": "비밀번호를 입력하세요.",
	"err_email_Check": "사용할 이메일 주소를 입력하여 주십시오.",
	"err_host_Name": "호스트명을 입력하여 주십시오.",
	"err_sourceIP": "출발지 네트워크 IP 주소를 입력하여 주십시오.",
	"err_ipv6address_CheckRange": "사용할 IPv6 주소 범위를 입력하여 주십시오. (예, 2001::1-2001::2)",
	"err_password_WEPCheck": "비밀번호를 13 자리로 입력하여 주십시오",
	"err_password_WPACheck": "비밀번호를 8 ~ 63 자리로 입력하여 주십시오",
	"err_check_DeviceAdminPassword": "비밀번호를 6 ~ 15 자리로 입력하여 주십시오",
	"err_check_IllegalChar": "사용하실 수 없는 문자가 입력되어 있습니다",
	"err_hex_Range": "0 ~ FF 사이의 값으로 입력하여 주십시오",
	"err_range_Compare": "마지막 주소가 시작 주소보다 커야 합니다",
	"err_number": "해당 값을 입력하여 주십시오",
	"err_ipv6": "IPv6 주소를 입력하여 주십시오.",
	"err_ipv6_PPPoE_Type": "IPv4 연결 방식이 PPPoE 로 설정되어 있어야 합니다",
	"err_ipv6_DsLite_Type": "당신은 인터넷에 액세스하는 대신 'DS 라이트'가 아닌 다른 IPv4의 인터넷 연결 모드를 선택해야합니다.",
	"err_wan_lan_conflict": "LAN 서브넷과 WAN 서브넷 충돌.",
	"err_Check_Mac": "Please enter a valid MAC address.",
	"err_mac_conflict": "The MAC address has existed.",

	"Features": "기능",
	"Device Mode": "장치 모드",
	"Router Mode": "라우터 모드",
	"Bridge Mode": "브리지 모드",
	"The device is changing to bridge mode.": "장치가 브리지 모드 로 변경 된다 .",
	"The device is changing to router mode.": "장치는 라우터 모드 로 변경 된다 .",


	"<b>Note</b>: If you are using a PPPoE connection, you will need to remove or disable any PPPoE client software running on your computers. ": "<b>참고</b> : PPPoE 옵션을 사용하는 경우, 컴퓨터에 있는 PPPoE 클라이언트 소프트웨어를 제거하거나 사용하지 않도록 설정하시기 바랍니다. ",
	"3G/4G Network": "3G/4G 방식",
	"Add Profile": "프로필 추가",
	"Are you sure you want to change your Internet connection type?": "인터넷 연결 유형을 변경 하시겠습니까?",
	"Browse": "찾아보기",
	"Country": "국가",
	"DHCP Client": "DHCP 클라이언트",
	"Dial-up Number": "전화 번호",
	"Dynamic PPPoE": "유동 PPPoE",
	"Guest Zone 5GHz Secondary": "5GHz 보조 게스트 존",
	"Hotspot": "핫스팟",
	"Hotspot Network Name(SSID)": "핫스팟 네트워크 이름 (SSID)",
	"Interface is not ready, please check again.": "인터페이스가 아직 준비되지 않았습니다. 다시 확인하여 주십시오.",
	"Internet Profiles": "인터넷 프로필",
	"Internet Profiles are networks you want the device to remember and reconnect to in the future. Profiles are created automatically the first time you connect to a particular network, and some profiles may require additional information from your Internet service provider.": "인터넷 프로필을 장치에 저장하고 나중에 재연결 할 수 있습니다. 프로필은 특정 네트워크 연결 시 자동으로 생성되며, 일부 프로필은 인터넷 공급 업체(ISP)에 추가 정보를 요청 할 수 있습니다.",
	"IP Address (Reserved)": "IP 주소 (예약 됨)",
	"ISP": "인터넷 공급 업체",
	"Profile Name": "프로필 이름",
	"SIM Card Status": "SIM 카드 상태",
	"The selected profile does not connect to Internet. Please recheck the configuration of the profile.": "선택한 프로필이 인터넷과 연결이 되지 않습니다. 프로필 파일을 다시 확인하여 주십시오.",
	"The selected profile is not configured.": "선택한 프로필은 올바른 구성이 아닙니다.",
	"This page shows you your current firmware version and language pack, and allows you to check for and download new firmware. After downloading the firmware, you can then upgrade it by using the buttons below. If you are using a language pack, we recommend that you also get the latest version of the language pack when upgrading the firmware to ensure that any changes in the interface are shown correctly.": "이곳에서 공유기의 현재 펌웨어 버전과 언어팩을 확인할 수 있으며 최신 펌웨어를 다운로드 받아 업그레이드 할 수 있습니다. 펌웨어를 업그레이드 후 인터페이스의 변경 사항이 정상적으로 표시되도록 언어 팩을 최신 버전으로 유지하여 주시기 바랍니다.",
	"Type": "유형",
	"Use this section to configure your Internet Connection profiles. If you are not sure what settings to use, please contact your Internet Service Provider.": "이곳에서 인터넷 연결 프로필을 구성할 수 있습니다. 설정 방법을 모를 경우, 인터넷 공급 업체(ISP)에 문의하시기 바랍니다.",
	"Wi-Fi 5GHz Secondary": "보조 Wi-Fi 5GHz",
	"Your setting would be take effect.": "설정을 저장하고 있습니다.",
	"It will take effect after reconnecting": "재연결 후 접속 됩니다.",
	"Disonnected": "연결이 끊김",
	"Connected": "연결되었습니다.",
	"terms and conditions.": "이용 약관",


	"Quick VPN": "퀵 VPN",
	"Quickly and easily create a profile for secure remote access to a Local Area Network (LAN). This profile can be used to configure other devices to connect to your LAN via a secure VPN tunnel.": "빠르고 쉽게 로컬 영역 네트워크 (LAN)에 보안 원격 액세스에 대한 프로필을 만들 수 있습니다. 이 프로파일은 보안 VPN 터널을 통해 LAN에 연결하는 다른 장치를 구성 할 수 있습니다.",
	"L2TP over IPSec": "IPSec을 통한 L2TP",
	"Authentication Protocol": "인증 프로토콜",
	"Save Configuration To Local Hard Drive": "로컬 하드 드라이브에 구성 저장",
	
	
	
	"The admin password is used to log in to this configuration interface.<br>It is highly recommended that you create a password to keep your device secure.": "관리자 비밀번호는 공유기의 설정화면 접속시 사용됩니다. 공유기의 보안을 위해 비밀번호를 설정하시기 바랍니다.",
	"This page lets you save or restore your device's current settings. You can also reset your device to the factory defaults or reboot the device. Please note that resetting your device will erase all settings and rules you have created.": "이 곳에서는 현재 공유기 설정을 파일로 저장, 파일에서 설정 복구, 공유기 공장 초기화, 또는 장치 재부팅을 할 수 있습니다. 공장 초기화 시 사용자가 설정한 모든 설정이 삭제되므로 주의하시기 바랍니다.",
	"(minutes)": "(분)",
	"(compatibility for some DHCP Clients)": "(일부 DHCP 클라이언트와 호환하기 위해 사용합니다.)",
	".": ".",
	"Language packs must be in .lng format; please try again.": "언어팩 파일의 확장자가 lng 형식이어야 합니다. 다시 확인하여 주십시오.",
	"Firmware files must be in .bin format; please try again.": "펌웨어 파일의 확장자가 bin 형식이어야 합니다. 다시 확인하여 주십시오.",
	"Please enter a value between 0 and FF.": "16진수로 입력하여 주십시오. (0~9/A~F/a~f)",
	"Day hour minute second": "일 시 분 초",
	"Please enter a password that is 10 hex digits long.": "16진수를 이용하여 10자리의 비밀번호를 입력하여 주십시오.",
	"Please enter a password that is 13 ASCII characters long.": "ASCII 코드를 이용하여 13자리의 비밀번호를 입력하여 주십시오.",
	"Please enter a DHCP Lease Time between 1 and 10800.": "DHCP IP 임대 시간을 1~10800 사이의 값으로 입력하여 주십시오.",
	"2.4GHz Wi-Fi Name (SSID)": "2.4GHz Wi-Fi 이름(SSID)",
	"20 MHz": "20 MHz",
	"Please enter a password that is 26 hex digits long.": "16진수를 이용하여 26자리의 비밀번호를 입력하여 주십시오.",
	"A 3G/4G broadband profile was not retrieved or the dial-up attempt failed.": "3G/4G 연결 프로파일을 수신하지 못하였거나 전화 연결을 하지 못하였습니다.",
	"3G/4G Data": "3G/4G 데이터",
	"3G/4G Wireless USB": "3G/4G USB 방식",
	"Please enter a password that is 5 ASCII characters long.": "ASCII 코드를 이용하여 5자리의 비밀번호를 입력하여 주십시오.",
	"5GHz Wi-Fi Name (SSID)": "5GHz Wi-Fi 이름(SSID)",
	"Copy to 5GHz": "5GHz 도 동일하게 설정",
	"Between 8 and 63 characters": "8 - 63 자",
	"Mixed 802.11ac/a/n": "802.11ac+a+n 혼용",
	"Mixed 802.11ac/n": "802.11ac+n 혼용",
	"Mixed 802.11g/b": "802.11b+g 혼용",
	"Mixed 802.11n/g": "802.11n+g 혼용",
	"AirPlay Status": "AirPlay 상태",
	"APN": "APN",
	"CHAP": "CHAP",
	"Please enter valid IP values (0-254) for the DHCP IP address range.": "DHCP IP 주소 범위를 0~254 사이의 값으로 입력하여 주십시오.",
	"DHCP Network": "DHCP 네트워크",
	"The DHCP Lease Time field cannot be blank.": "DHCP 임대 시간을 입력하여 주십시오.",
	"DHCP Lease Time must between 1~10800.": "DHCP 임대 시간을 1 ~ 10800 사이의 값으로 입력하여 주십시오.",
	"DLNA (Digital Living Network Alliance) is the standard for the interoperability of Network Media Devices (NMDs).": "DLNA (Digital Living Network Alliance)는 네트워크 미디어 장치의 상호 컨텐츠 공유를 위한 표준 규격입니다.",
	"DLNA (Digital Living Network Alliance) is the standard for the interoperability of Network Media Devices (NMDs). The user can enjoy multi-media applications (music, pictures and videos) on your network connected PC or media devices. Web File Access allows you to use a web browser to remotely access files stored on an SD card or USB storage drive plugged into the router.": "DLNA (Digital Living Network Alliance)는 네트워크 미디어 장치의 상호 컨텐츠 공유를 위한 표준 규격입니다. 네트워크에 연결된 PC나 미디어 장치의 멀티미디어 어플리케이션을 통해 사용이 가능합니다. 웹 브라우저를 사용하여 공유기에 연결된 USB 저장장치나 SD 카드에 저장된 파일에 접속할 수 있습니다.",
	"DLNA technology allows you to enjoy your media anywhere, anytime in your home with DLNA-certified devices. Your music can be streamed wirelessly from DLNA-certified DMS (Digital Media Server) devices. You can also stream music to the speaker connects to your device through iOS device at home effortlessly.": "DLNA 기술은 가정에서 DLNA가 지원되는 장치에 있는 미디어를 제약없이 사용할 수 있도록 도와줍니다. DLNA가 지원되는 DMS(디지털 미디어 서버)에 있는 음악이나 동영상을 을 무선으로 재생할 수 있습니다.",
	"DLNA Renderer": "DLNA 단말",
	"DLNA Renderer Status": "DLNA 단말 상태",
	"DLNA Media Server Name": "DLNA 미디어 서버 이름",
	"Enable DMZ": "DMZ 호스트 사용",
	"DNS": "DNS",
	"DNS Server": "DNS 서버",
	"Please enter a dns server.": "DNS 서버 주소를 입력하여 주십시오.",
	"DS-Lite": "DS-Lite",
	"Dynamic IP (L2TP)": "유동 IP (L2TP)",
	"Dynamic IP (PPPoE)": "유동 IP (PPPoE)",
	"Dynamic IP (PPTP)": "유동 IP (PPTP)",
	"GatewayWithWiFi": "Wi-Fi 게이트웨이",
	"HT20/40 Coexistence": "HT20/40 자동 전환",
	"http": "HTTP",
	"IP": "IP",
	"IP / Domain name": "IP / 도메인 이름",
	"Please enter or select an IP address.": "IP 주소를 입력하거나 선택하여 주십시오.",
	"The IP pool range is invalid.": "IP 주소 할당 범위가 올바르지 않습니다.",
	"Ipv4": "IPv4",
	"IPv4 Device Management Interface": "IPv4 장치 관리 인터페이스",
	"IPv6 Default Gateway": "IPv6 기본 게이트웨이",
	"Ipv6": "IPv6",
	"Please enter a IPv6 dns server.": "IPv6 DNS 서버 주소를 입력하여 주십시오.",
	"Please enter a IPv6 gateway address.": "IPv6 게이트웨이 주소를 입력하여 주십시오.",
	"The IPv6 rule section is an advance feature used to deny or allow traffic from passing through the device.": "이곳에서는 장치를 통과하는 트래픽의 차단 또는 허용하는 IPv6 규칙을 설정 할 수 있습니다.",
	"IPv6 Device Management Interface": "IPv6 장치 관리 인터페이스",
	"Kbits/sec": "Kbits/sec",
	"L2TP Server": "L2TP 서버",
	"The LAN IP address cannot be the same as the WAN IP address.": "로컬 IP 주소는 인터넷 IP 주소와 다르게 설정하여 주십시오.",
	"The LAN IPv6 Link-Local Address is the IPv6 Address that you use to access the Web-based management interface.": "LAN IPv6 Link-Local 주소는 공유기의 설정화면에 접속할 수 있는 IPv6 주소입니다.",
	"LAN subnet conflicts with WAN subnet.": "LAN 서브넷과 WAN 서브넷이 충돌됩니다. 다시 확인하여 주십시오.",
	"MAC Address Clone": "MAC 주소 복사",
	"mydlink Regristration": "mydlink 등록 완료",
	"I accept the mydlink": "mydlink 설정 허용",
	"Could not connect to mydlink; please check your Internet connection.": "Mydlink 서비스에 연결할 수 없습니다. 인터넷 연결을 확인하여 주십시오.",
	"Update Time Using an NTP Serevr": "NTP 서버 동기화 사용함",
	"PAP": "PAP",
	"PIN Code": "PIN 코드",
	"The PPPoE user name or password is incorrect.": "PPPoE 사용자 이름 또는 비밀번호가 올바르지 않습니다.",
	"PPTP Server": "PPTP 서버",
	"SD Card": "SD 카드",
	"The SD card has an unsupported file system format.": "SD 카드가 지원되지 않는 파일형식으로 포맷되어 있습니다.",
	"To access your storage with SharePort Web Access, click here.": "SharePort 웹액세스로 스토리지에 접속하려면, 이곳을 클릭하여 주십시오.",
	"SSID": "SSID",
	"Static IP (L2TP)": "고정 IP (L2TP)",
	"Static IP (PPPoE)": "고정 IP (PPPoE)",
	"Static IP (PPTP)": "고정 IP (PPTP)",
	"Static IP (Static)": "고정 IP (Static)",
	"This page lets you enable and configure a Wi-Fi Guest Zone. Users connected to a Guest Zone cannot communicate or detect devices on your home network unless Internet Access Only is disabled under Home Network Access.": "이곳에서 Wi-Fi 게스트 존에 대해 설정할 수 있습니다. 게스트 존에 연결된 사용자는 내부 네트워크 연결 차단 설정 시 홈 네트워크에 연결된  다른 단말에 대한 검색이나 통신을 할 수 없습니다.",
	"UPnP Media Server": "UPnP 미디어 서버",
	"USB": "USB",
	"The USB drive has an unsupported file system format.": "USB 드라이브가 지원되지 않는 파일형식으로 포맷되어 있습니다.",
	"USB Storage": "USB 저장 장치",
	"VIRTUAL": "가상",
	"WAN IP Address": "WAN IP 주소",
	"WEP": "WEP",
	"SELECT WI-FI NETWORK": "Wi-Fi 네트워크 선택",
	"WI-FI CONNECTION SETUP WIZARD": "Wi-Fi 연결 설정 마법사",
	"Wi-Fi 5GHZ": "5GHz Wi-Fi",
	"Wi-Fi Clients(Guest Zone)": "Wi-Fi 단말(게스트 존)",
	"Wi-Fi networks": "Wi-Fi 네트워크",
	"Wi-Fi Network Name": "Wi-Fi 네트워크 이름",
	"Wi-Fi Network Name (SSID)": "Wi-Fi 네트워크 이름 (SSID)",
	"To setup a Wi-Fi Network you will need to give your Wi-Fi Nerwork a Name(SSID) and Password.": "Wi-Fi 네트워크 설정을 위해  Wi-Fi Network 이름(SSID)과 비밀번호를 입력하여 주십시오.",
	"To setup a Wi-Fi network you will need to give your Wi-Fi network a name(SSID) and password.": "Wi-Fi 네트워크 설정을 위해  Wi-Fi Network 이름(SSID)과 비밀번호를 입력하여 주십시오.",
	"The Wi-Fi connection is not secure.": "선택하신 Wi-Fi는 보안이 설정되어 있지 않습니다.",
	"ENTER WIFI PASSWORD": "Wi-Fi 비밀번호 입력",
	"Wi-Fi Hotspot Client": "Wi-Fi Hot-Spot 단말",
	"xDSL BroadBand (PPPoE)": "XDSL 광대역 (PPPoE)",
	"xDSL Broadband (PPPoE)": "XDSL 광대역 (PPPoE)",
	"xDSL Broadband(PPPoE)": "XDSL 광대역 (PPPoE)",
	"VIRTUAL PUSH BUTTON": "가상 푸쉬 버튼",
	"The Virtual Server option allows you to define a single public port on your router for redirection to an internal LAN IP Address and Private LAN port if required. This feature is useful for hosting online services such as FTP or Web Servers.": "가상서버 옵션을 사용할 경우 내부 LAN IP 주소와 사설 LAN 포트로 전송하기 위한 단일 공용 포트를 공유기에 지정할 수 있습니다. 이 기능은 FTP나 웹서버와 같은 온라인 서비스 호스팅 사용에 유용합니다.",
	"Before Sign up mydlink, the Admin Password of DIR-508L can not be blank.": "Mydlink 서비스에 등록하기 전에, DIR-885L 의 관리자 비밀번호를 설정하여 주십시오.",
	"Please enter a value.": "올바른 값을 입력하여 주십시오.",
	"Please enter the Personal Identification Number(PIN) code.": "개인 식별 번호(PIN)를 입력하여 주십시오.",
	"Search Songs...": "음악 검색...",
	"Search Movie...": "영화 검색...",
	"Guest Zone Wi-Fi Name (SSID)": "게스트 존 Wi-Fi 이름 (SSID)",
	"Continue": "계속",
	"Always Enable": "항상 사용",
	"Advanced Settings...": "고급 설정 ...",
	"Vender": "공급 업체",
	"Restore Factory Defaults": "공장 초기화",
	"Reset To Factory Defaults": "공장 초기화",
	"Reset To Factory Default Settings": "공장 초기화",
	"The admin password is used to log in to this configuration interface. It is highly recommended that you create a password to keep your router secure.": "관리자 비밀번호는 공유기의 설정화면 접속 시 사용됩니다. 공유기의 보안을 위해 비밀번호를 설정하시기 바랍니다.",
	"Please set your Admin Password at least six characters.": "관리자 비밀번호는 8자 ~ 15자의 숫자, 영어, 특수문자를 혼합하여 설정하시기 바랍니다.",
	"The admin password is used to log in to this configuration interface.": "관리자 비밀번호는 공유기의 설정화면 접속 시 사용됩니다.",
	"SELECT CONFIGURATION METHOD": "설정 방법 선택",
	"Save Configuration To File": "설정을 파일로 저장",
	"Routing Between Zones": "구역 간 라우팅",
	"Your password must be 13 or 26 characters length.": "Wi-Fi 비밀번호를 13자리 또는 26자리로 입력하여 주십시오.",
	"Your password must be 5 or 10 characters length.": "Wi-Fi 비밀번호를 5자리 또는 10자리로 입력하여 주십시오.",
	"Your password must be between 6-15 characters length.": "비밀번호를 6 ~ 15자 범위에서 입력하여 주십시오.",
	"Your password must be at least 8 characters long.": "비밀번호를 최소 8자리로 입력하여 주십시오.",
	"Your password must be between 8-63 characters length.": "Wi-Fi 비밀번호를 8 ~ 63 자 범위에서 입력하여 주십시오.",
	"Use this section to configure the internal network settings of your Extender. Device Name allows you to configure this device more easily when your network using TCP/IP protocol. You can enter the device name of the Extender into your web browser to access the instead of IP address for configuration. Recommend to change the device name if there're more than one D-Link devices within the subnet.": "이곳에서 익스텐더의 내부 네트워크 설정을 할 수 있습니다. 장치명은 네트워크에 TCP/IP 프로토콜을 사용하는 경우 쉽게 장치를 설정할 수 있도록 합니다. 웹 브라우저에 IP 주소 대신 익스텐더 장치명을 입력하여 설정 화면에 접속할 수 있습니다. 네트워크 내에 하나 이상의 D-Link 기기가 있다면 장치명을 변경하는 것이 좋습니다.",
	"Add Rules": "규칙 추가",
	"It is highly recommended that you create a password to keep your router secure.": "공유기의 보안을 위해 비밀번호를 설정하시기 바랍니다.",
	"Do you have an existing mydlink account": "기존 mydlink 계정을 가지고 있습니까?",
	"Others": "기타",
	"I accept the mydlink terms and conditions.": "Mydlink 사용권 및 조항에 동의합니다.",
	"My IPv6 Connection is": "IPv6 연결 방식",
	"My LAN Connection is": "LAN 연결 방식",
	"My Access Device Hard Drive": "하드 드라이브 접속 장치",
	"The built-in UPnP media server streams music, videos, and photos stored on an attached USB drive to PCs, smartphones, tablets, smart TVs, or other media devices on your network. Web File Access allows you to access files on an attached USB drive through a web browser.": "UPnP 미디어 서버 기능을 통해 공유기에 USB 드라이브에 저장된 음악, 동영상, 사진 파일을 네트워크에 있는 PC, 스마트폰, 테블릿, 스마트 TV 등의 미디어 장치에서 실시간으로 재생할 수 있습니다. 웹 파일 접속은 공유기에 연결된 USB 드라이브에 웹 브라우저를 통해 접속 할 수 있도록 합니다.",
	"Yes, I have a mydlink account.": "네. Mydlink 계정을 가지고 있습니다.",
	"Network (LAN)": "네트워크 (LAN)",
	"Secure your network": "네트워크 보안",
	"Network Name(SSID)": "네트워크 이름(SSID)",
	"Choose a Network...": "네트워크 선택 ...",
	"(Year/ Month/ Day)": "(년/ 월/ 일)",
	"Connect to another uplink router": "다른 공유기에 연결",
	"Downloading...": "다운로드 중...",
	"Use the following IPv6 DNS Servers.": "다음 IPv6 DNS 서버 사용",
	"Diagram": "구성도",
	"Are you sure you want to reset the device to its factory default settings?,": "장치를 공장 초기화 하시겠습니까?",
	"You can access your music, pictures and videos from a PC or media device connected to your network.": "네트워크에 연결된 PC 혹은 미디어 장치에서 음악, 사진 및 동영상에 접속할 수 있습니다.",
	"Are you sure you want to delete": "삭제 하시겠습니까?",
	"You have successfully registered this device to your mydlink account.": "Mydlink 계정 등록이 완료되었습니다.",
	"You can only specify up to 5 folders for access.": "접속할 수 있는 폴더를 최대 5개까지 지정할 수 있습니다.",
	"You can change the default device name with another unique name for audio renderer service. Eg. Living Room.": "오디오 단말 서비스를 위해 기존 장치명을 구분하기 쉬운 다른 이름으로 변경 할 수 있습니다. 예) Living Room",
	"Enter the IPv6 address information that you would like to use to access the Web-based management interface.": "설정 화면에 접속하기 위한 IPv6 주소를 입력하여 주십시오.",
	"If you changed the device name you may need to change the IP address in browse to access the device.": "장치명을 변경 한 경우 장치에 접속하기 위해 IP 주소를 변경해야 할 수 있습니다.",
	"Are you sure you want to reboot the device?,": "장치를 재부팅 하시겠습니까?",
	"Are you sure you want to reset the device?": "장치를 공장 초기화 하시겠습니까?",
	"You have failed to connect to the Wi-Fi network within the given timeframe, please click on the button below to do it again.": "Wi-Fi 네트워크 연결 시간이 초과되었습니다. 다시 시도하여 주십시오.",
	"Use this section to configure the wireless settings for your D-Link Extender. Please note that changes made on this section may also need to be duplicated on your Wireless Client.": "이곳에서 D-Link 익스텐더에 대한 무선 설정을 할 수 있습니다. 변경한 설정에 따라 무선 클라이언트를 다시 연결해야 합니다.",
	"Use this section to configure the wireless settings for your D-Link Router. Please make sure that any changes made in this section will need to be updated on your wireless device.": "이곳에서 D-Link 공유기의 무선 설정을 구성할 수 있습니다. 변경한 설정에 따라 무선 클라이언트를 다시 연결해야 합니다.",
	"Checking Your Internet connectivity": "인터넷 연결을 확인 중 입니다.",
	"Do you want to continue?": "계속 진행하시겠습니까?",
	"Please press Push Button(Physical or Virtual) on the AP or Router you are connecting to within": "연결하려는 AP나 공유기의 WPS 버튼을 눌러 주시기 바랍니다.",
	"Select this option if you want to setup your network manually": "수동으로 네트워크 설정을 진행하시려면, 이 항목을 선택하여 주십시오.",
	"Use this section to configure the Wi-Fi Network you would like your DCH-M225 to connect to. Use Site Survey to scan available Wi-Fi networks and select the Wi-Fi Network you would like your DCH-M225 to connect to. Enter the Password of the Wi-Fi Network you selected and click Save.": "이곳에서 DCH-M225의 Wi-Fi 네트워크 설정을 할 수 있습니다. 무선 검색을 통해 사용 가능한 Wi-Fi를 스캔하고 연결하고자 하는 Wi-Fi 네트워크를 선택합니다. 선택한 Wi-Fi 네트워크의 비밀번호를 입력하고 저장합니다.",
	"QoS prioritizes your network traffic so you can decide what devices should have priority over other devices. For example, you could set a computer that is downloading files to have lower priority than a laptop that is streaming movies to ensure that you can stream movies smoothly without downloads taking up all of your bandwidth.": "QoS는 네트워크 트래픽의 우선 순위를 정하여 특정 장치의 트래픽을 우선적으로 처리할 수 있도록 합니다. 예를 들어, 파일을 다운로드하는 컴퓨터의 대역폭을 낮은 우선 순위로 정해 영화를 스트리밍하는 노트북의 대역폭 우선적으로 보장할 수 있습니다.",
	"Dynamic DNS (DDNS) allows you to use an easy to remember domain name such as www.[YourDomainName].com to reach your router's dynamically assigned IP address. This is useful when hosting a web, FTP, or game server, and allows you to reach your server no matter what your IP address has changed to. D-Link offers a free DDNS service that you can use through www.DLinkDDNS.com.": "Dynamic DNS 설정은 인터넷 공급 업체(ISP)로부터 할당 받은 유동 IP 주소를 [도메인 이름].COM과 같이 기억하기 쉬운 이름과 연결시켜 주는 기능입니다. 이 기능은 가상 서버를 사용할 때 유용합니다. D-Link는 www.dlinkddns.com을 통해 DDNS 서비스를 무료로 제공합니다.",
	"Router Advanced Lifetime": "공유기 고급 라이프타임",
	"The router is not connected to the Internet.": "공유기가 인터넷에 연결되어 있지 않습니다.",
	"The Router will not be reprogrammed.,": "공유기 설정을 재구성할 수 없습니다.",
	"Login": "로그인",
	"Please switch your browser to normal mode before login.": "로그인하기 전에 브라우저를 일반 모드로 전환하십시오.",
	"local": "로컬",
	"Allow Local Access": "로컬 접속 허용",
	"Repeater": "리피터",
	"Netmask": "서브넷 마스크",
	"Matrix": "경로 설정 값",
	"All Devices": "모든 장치",
	"Destination IP": "목적지 IP",
	"Wireless": "무선",
	"Wireless Mode": "무선 모드",
	"Please enter Wi-Fi Password to establish wireless connection": "무선 연결할 Wi-Fi의 비밀번호를 입력하여 주십시오.",
	"Select this option if your wireless device supports WPS(Wi-Fi Protected Setup)": "무선 단말이 WPS 기능을 지원하는 경우, 이 옵션을 선택하여 주십시오.",
	"Search Documents...": "문서 검색...",
	"Firewall Setting": "방화벽 설정",
	"Battery": "배터리",
	"Web File Access cannot be used when the battery is low. Please charge the battery first.": "배배터리가 부족하면 웹 파일 접속을 사용할 수 없습니다. 먼저 배터리를 충전하십시오.",
	"The firmware cannot be upgraded when the battery is low. Please charge the battery first.": "배터리가 부족하면 웹 파일 접속을 사용할 수 없습니다. 먼저 배터리를 충전하십시오.",
	"The battery currently has less than 15% charge; please charge the battery before upgrading the firmware.": "현재 베터리의 충전상태가 15% 이하입니다. 펌웨어 업그레이드 전에 배터리를 충전하십시오.",
	"Your changes are being saved, you will soon be disconnected.": "변경 사항이 저장 되고 있습니다. 연결이 곧 끊어집니다.",
	"Security Check": "보안 확인",
	"Please note that when using WEP security, WPS will be disabled.": "보안방식을 WEP로 설정하는 경우, WPS 기능은 사용할 수 없습니다.",
	"Secondary IPv6 DNS Server": "보조 IPv6 DNS 서버",
	"Non-Registered": "미등록",
	"Disbled": "사용 안 함",
	"Click \"Next\" to find available Wi-Fi hotspot networks.": "사용 가능한 Wi-Fi 핫스팟 네트워크를 찾으려면 \"다음\"을 클릭하여 주십시오.",
	"Users": "사용자",
	"User List": "사용자 목록",
	"Edit User Settings": "사용자 설정을 편집합니다",
	"The admin has read/write access and can change passwords, while the user has read-only access. By default there is no password configured. It is highly recommended that you create a password to keep your router secure.": "admin 계정은 읽기/쓰기와 비밀번호 변경이 가능하지만, 사용자 계정은 읽기만 가능합니다. 기본적으로 비밀번호가 설정되어 있지 않습니다. 공유기의 보안을 위해 비밀번호를 설정하시기 바랍니다.",
	"Please enter an NTP server to use.": "NTP 서버 주소를 입력하여 주십시오.",
	"Invalid character": "사용 할 수 없는 문자",
	"Pictures": "사진",
	"Search Photos...": "사진 검색 ...",
	"Please select a file to delete.": "삭제 할 파일을 선택하여 주십시오.",
	"Create a New User": "새로운 사용자 만들기",
	"Check For New Firmware": "최신 펌웨어 확인",
	"New Folder": "새 폴더",
	"Documents": "문서",
	"Please enter a server address": "서버 주소를 입력 해주십시오",
	"SELECT": "선택",
	"You can block a device from accessing your network completely.": "설정된 스케줄에 따라 장치의 네트워크 접속을 차단할 수 있습니다.",
	"Setting and registering your router with mydlink will allow you to use its mydlink cloud services features, including online access and management of your router through the mydlink portal website.": "공유기를 mydlink 서비스에 등록하면, mydlink 포털 웹사이트 및 스마트 기기용 mydlink 어플리케이션을 통해 온라인으로 공유기 관리가 가능한 mydlink 클라우드 서비스 기능을 사용 할 수 있습니다.",
	"Creating a mydlink account and registering your router with mydlink will allow you to remotely monitor and manage your network on your smartphone or tablet, as well as through the secure web portal. It also allows you to plug in a USB drive and access the stored files from anywhere in the world through iOS and Android apps as well as the web browser on your computer.": "공유기를 mydlink 서비스에 등록하면, mydlink 포털 웹사이트 및 스마트 기기용 mydlink 어플리케이션을 통해 온라인으로 공유기 관리가 가능한 mydlink 클라우드 서비스 기능을 사용 할 수 있습니다.",
	"Your settings are being saved.": "설정을 저장하고 있습니다.",
	"Please check your settings and try again.": "설정을 확인하고 다시 시도하십시오.",
	"Setup Complete": "설치 완료",
	"Manual Time Confuguration": "수동 시간 설정",
	"Received": "수신",
	"Received (RX)": "수신 (RX)",
	"Scanning": "검색 중",
	"SCAN": "검색",
	"Speaker": "스피커",
	"(Hour/ Minute)": "(시/ 분)",
	"Time Confuguration": "시간 설정",
	"Connection Up Time": "연결 유지 시간",
	"Fail": "실패",
	"No, I want to create a new mydlink account.": "아니오, 새로운 mydlink 계정을 등록하겠습니다.",
	"No.": "아니오.",
	"Below is a summary of your Wi-Fi security and device password settings.Please take a note of your settings and save your configuration.": "아래는 공유기에 저장된 Wi-Fi 설정 및 관리자 페이지 접속 비밀번호입니다. 확인 후 설정을 저장하시기 바랍니다.",
	"Drag the device cards above to the Prioity boxes below.": "클라이언트 카드를 우선 순위 상자에 드래그하여 주시기 바랍니다.",
	"Drag the device cards above to the priority boxes below.": "클라이언트 카드를 우선 순위 상자에 드래그하여 주시기 바랍니다.",
	"Password length": "비밀번호 길이",
	"A password is required to join": "비밀번호를 입력하여 주십시오.",
	"The password field cannot be blank.,": "비밀번호를 입력하여 주십시오.",
	"Password is incorrect.": "비밀번호가 올바르지 않습니다.",
	"The password must contain at least 8 characters": "비밀번호는 반드시 8자 이상 입력하시기 바랍니다.",
	"No new firmware": "새로운 펌웨어가 없습니다.",
	"No language pack installed.": "언어팩이 설치되어 있지 않습니다.",
	"Language Pack Imformation": "언어 팩 정보",
	"Uplink Router": "업링크 공유기",
	"Upgrading...": "업그레이드 중...",
	"The Upgrade process cannot be cancelled, and this page must stay open until the the process is complete!": "업그레이드는 취소 할 수 없으며, 완료 될 때까지 이 페이지를 유지해야합니다!",
	"Before performing an upgrade, be sure to save the current configuration from the Management-System screen. Do you still want to upgrade?,": "업그레이드를 수행하기 전에, 관리 시스템 화면에서 현재 설정을 저장해야합니다. 업그레이드 하시겠습니까?",
	"The uploaded file may not be correct. You may have uploaded a file that is not intended for this router, or the uploaded file may be corrupted.,": "업로드 된 파일은 정확하지 않을 수 있습니다. 강제로 파일을 업로드하면  공유기가 오작동 할 수 있습니다.",
	"If the uploaded file is correct, it is possible that the router may be too busy to properly receive it right now. In this case, please try the upload again.,": "공유기에 업로드 된 파일이 올바른 경우에도 다른 작업으로 인해 실패 할 가능성이 있습니다. 이 경우, 다시 업로드 하시기 바랍니다.",
	"The uploaded firmware file may be corrupted; please check the file or try downloading it again.": "업로드 된 펌웨어 파일에 손상이 있을 수 있습니다. 파일을 재확인하거나 다시 다운로드를 시도하시기 바랍니다.",
	"Please select a folder to allow access to.": "접속할 수 있는 폴더를 선택하여 주십시오.",
	"Please choose one site to connect to.": "연결 할 사이트를 선택하여 주십시오.",
	"Air Play": "Air Play",
	"Please note that making changes here may require you to change the wireless settings on your other devices.,": "이곳에서 설정을 변경하는 경우 무선 단말을 변경된 설정에 맞게 다시 연결해야 합니다.",
	"Here, you can set up various firewall features to protect your network from attacks. You can click on the DMZ, IPv4 Rules, and IPv6 Rules buttons to see the settings for that feature.": "이곳에서 네트워크에 대한 공격을 차단할 수 있는 다양한 방화벽 기능을 설정할 수 있습니다. DMZ, IPv4 규칙, IPv6 규칙등을 선택하여 해당 기능에 대한 설정 확인이 가능합니다.",
	"Here, you can configure the Wi-Fi network settings for your router.": "이곳에서, 공유기의 Wi-Fi 네트워크 설정을 구성할 수 있습니다.",
	"Here, you can configure the various storage sharing features of your router. The DLNA server allows you to stream stored pictures, music, and video to another DLNA-compatible device on your network. Web File Access allows you to use a web browser to access stored files from a PC connected to your network.": "이곳에서 다양한 스토리지 공유 기능을 설정 할 수 있습니다. DLNA 서버 기능을 사용하면 USB 저장장치에 저장되어 있는 사진, 음악, 동영상을 네트워크의 다른 DLNA 지원 기기에서 감상할 수 있습니다. 웹파일 접속 기능을 사용하면 USB 저장장치에 저장되어 있는 파일을 네트워크의 다른 PC에서 접속하여 사용할 수 있습니다.",
	"Here, you can see a list of all devices connected to your Wi-Fi network. Click on a device's pencil icon for further options.": "이곳에서 Wi-Fi에 연결된 모든 장치의 목록을 볼 수 있습니다. 추가 옵션에 대해 확인하려면 장치의 [연필] 아이콘을 클릭하시기 바랍니다.",
	"Here, you can see a list of all devices connected to your Wi-Fi Guest Zone. Click on a device's pencil icon for further options.": "이곳에서 게스트 존에 연결된 모든 장치의 목록을 볼 수 있습니다. 추가 옵션에 대해 확인하려면 장치의 [연필] 아이콘을 클릭하시기 바랍니다..",
	"Here, you can configure the local network settings for your router, including the IP address you use to access this configuration interface. Please note that if you change this IP address, you will need to use the new IP to access this interface.": "이곳에서 공유기의 설정 화면에 접속할 수 있는 LAN IP 주소와 네트워크에 대한 설정을 변경 할 수 있습니다. 공유기의 LAN IP 주소를 변경 한 경우 공유기 설정 화면에 다시 접속하기 위해서 브라우저에 변경된 IP 주소를 입력해야 합니다.",
	"Connection type": "연결 유형",
	"Connecting...": "연결 중 ...",
	"Operator": "오퍼레이터",
	"Video": "비디오",
	"Yes": "예",
	"Reserved IP": "예약 IP",
	"Audio Renderer": "오디오 렌더러",
	"Please enter a name for your Audio Renderer.": "오디오 렌더러의 이름을 입력하여 주십시오.",
	"On Demand": "필요 시",
	"The Website Filter option allows you to set up a list of Web sites you would like to allow or deny through your network. To use this feature, you must also select the \"Apply Web Filter\" checkbox in the Access Control section.": "웹 사이트 필터 옵션을 사용하여 특정 웹 사이트에 대한 접속을 허용하거나 차단할 수 있습니다. 이 기능을 사용하려면 웹 사이트 필터 메뉴에서 “거부“ 또는 “허용“을 선택하고 웹 사이트 URL/도메인 규칙에 추가해야 합니다.",
	"Web File Access Login": "웹 파일 접속 로그인",
	"Log in to the web file access Server": "웹 파일 서버 로그인",
	"Web File Access allows you to use a web browser to remotely access files store on an SD card or USB storage drive plugged into the router.": "웹 파일 접속을 사용하면 웹 브라우저를 사용하여 공유기에 연결된 USB 저장장치에 저장되어 있는 파일에 원격으로 접속할 수 있습니다.",
	"Here, you can see a list of all devices connected through an Ethernet cable. Click on a device to view more information about it, or click on the pencil icon to give the device a name to make it easy to identify. You can block a device from accessing your network always or according to a schedule by using the Block dropdown box.": "이곳에서 이더넷 케이블로 연결된 모든 장치의 목록을 볼 수 있습니다. 장치에 대한 정보를 확인하거나 장치 구분을 위한 이름 변경 설정을 하시려면 [연필] 아이콘을 클릭하시기 바랍니다. 자녀보호 기능을 통해 장치의 인터넷 사용 시간을 설정할 수 있습니다.",
	"Please enter a valid username and password.": "유효한 사용자 이름과 비밀번호를 입력하여 주십시오.",
	"Music": "음악",
	"Please Take a note of the following summary of your Wi-Fi Security setting for furture reference": "무선 단말의 연결을 위해 Wi-Fi 보안 설정을 확인하시기 바랍니다.",
	"Scanning for Wi-Fi hotspot networks…": "Wi-Fi 핫스팟 네트워크를 검색 중...",
	"Use this page to configure the local network settings for your router, including the IP address you use to access this configuration interface. Please note that if you change this IP address, you will need to use the new IP to access this interface.": "이곳에서 공유기의 설정 화면에 접속할 수 있는 LAN IP 주소와 네트워크에 대한 설정을 변경 할 수 있습니다. 공유기의 LAN IP 주소를 변경 한 경우 공유기 설정 화면에 다시 접속하기 위해서 브라우저에 변경된 IP 주소를 입력해야 합니다.",
	"Use this section to configure the network settings for your device. You can enter a name for your device in the management link field, and use the link to access web UI in a web browser. Recommend to change the management link if there are more than one D-Link devices within the network.": "이곳에서 장치에 대한 네트워크 설정을 할 수 있습니다. 관리 링크 이름을 설정하면 웹 브라우저에서 이 관리 링크 이름을 이용하여 웹 UI에 접속할 수 있습니다. 네트워크 내에 하나 이상의 D-Link 기기가 있다면 장치명을 변경하는 것이 좋습니다.",
	"This wizard is designed to assist you in your Wi-Fi network setup. It will guide you through step-by step instructions on how to set up your Wi-Fi network and how to make it secure.": "이 마법사는 단계별 과정을 통해 안전하게 Wi-Fi 네트워크를 설정 할 수 있도록 안내 할 것 입니다.",
	"To setup this Internet connection, you will need to have a User Name from your InternetService Provider. If you do not have this information, please contact your ISP.": "이 인터넷 연결을 설정하려면, 인터넷 공급자(ISP)로 부터 제공받은 사용자 이름이 필요합니다. 이 정보가 없는 경우, 인터넷 공급 업체(ISP)에 문의하시기 바랍니다.",
	"This page lets you configure a Wi-Fi Guest Zone. Wi-Fi Guest Zones are Wi-Fi networks that are separate from your normal ones, and use different Wi-Fi Network Names and passwords. Users connected to a Guest Zone cannot communicate or detect devices on your normal network unless the Access Local Service option is enabled. Guest Zones are useful to give guests Internet access without allowing them to access your own devices on your network.": "이곳에서 Wi-Fi 게스트 존을 구성할 수 있습니다. Wi-Fi 게스트 존은 일반 Wi-Fi와는 다른 별개의 Wi-Fi 네트워크 이름(SSID)과 비밀번호를 사용합니다. 게스트 존에 연결된 사용자는 내부 네트워크 연결 차단 설정 시 네트워크의 다른 단말을 검색하거나 통신할 수 없고 인터넷 사용만 가능합니다.",
	"This page shows you your current firmware version and language pack, and allows you to check for and download new firmware. After downloading the firmware, you can then upgrade it by using the buttons below. If you are using a language pack, we recommend that you also get the latest version of the language pack when upgrading firmware to ensure that any changes in the interface are shown correctly.": "이곳에서 공유기의 현재 펌웨어 버전과 언어팩을 확인할 수 있으며 최신 펌웨어를 다운로드 받아 업그레이드 할 수 있습니다. 펌웨어를 업그레이드 후 인터페이스의 변경 사항이 정상적으로 표시되도록 언어 팩을 최신 버전으로 유지하여 주시기 바랍니다.",
	"This page allows you to define custom routes to define how data traffic is moved around your network.": "이곳에서 데이터의 네트워크 이동 경로를 직접 설정할 수 있습니다.",
	"This page allows you to set the router's internal system clock. You can set the time manually, or automatically through a time server.": "이곳에서 공유기의 시스템 시간을 설정할 수 있습니다. 시스템 시간은 수동으로 설정하거나 시간 서버를 이용하여 자동으로 설정할 수도 있습니다.",
	"This page lets you save or restore your router's current settings. You can also reset your router to the factory defaults or reboot the router. Please note that resetting your router will erase all settings and rules you have created.": "이곳에서 공유기의 현재 설정을 저장하거나 복구할 수 있고 공장 초기화 및 재부팅을 할 수 있습니다. 공유기를 초기화하면 사용자가 만든 모든 설정과 규칙이 삭제됩니다.",
	"This page lets you configure a Wi-Fi Guest Zone, which lets you share Internet access with guests on a separate Wi-Fi network. Guests will be prevented from accessing devices on your home network unless Allow Local Access is enabled.": "이곳에서 기존 Wi-Fi 네트워크와 분리된 별도의 Wi-Fi 게스트 존을 설정할 수 있습니다. 게스트 존에 연결된 사용자는 내부 네트워크 연결 차단 설정 시 네트워크의 다른 단말을 검색하거나 통신할 수 없고 인터넷 사용만 가능합니다.",
	"This page gives you various statistics about data transmitted and received by your AP through the internet, and through your wireless networks.": "이곳에서는 공유기를 통한 유,무선 단말의 인터넷 사용량에 대한 통계를 볼 수 있습니다.",
	"This page allows you to enable logging of system events to a SysLog server, or to e-mail the log to you according to a schedule or when the log is full.": "이곳에서 시스템 이벤트 메시지를 Syslog 서버에 기록하도록 설정 할 수 있으며, 정해진 스케줄 혹은 로그가 가득 찼을 경우 설정된 이메일 주소로 메세지를 발송하도록 설정 할 수 있습니다.",
	"This page shows you your current firmware version, and allows you to check for and download new firmware. After downloading the firmware, you can then upgrade it by using the buttons below.": "이곳에서 공유기의 현재 펌웨어 버전을 확인할 수 있으며 최신 펌웨어를 다운로드 받아 업그레이드 할 수 있습니다.",
	"This page lets you enable and configure a Wi-Fi Guest Zone. Users connected to a Guest Zone cannot communicate or detect devices on your normal network unless Internet Access Only iis disabled under Home Network Access.": "이곳에서 Wi-Fi 게스트 존을 설정할 수 있습니다. 게스트 존에 연결된 사용자는 내부 네트워크 연결 차단 설정 시 네트워크의 다른 단말을 검색하거나 통신할 수 없고 인터넷 사용만 가능합니다.",
	"This folder has already been added.": "이 폴더는 이미 추가 되었습니다.",
	"This will cause all current settings to be lost.,": "현재의 모든 설정이 삭제될 수 있습니다.",
	"This IP address is already reserved for another device.": "이미 다른 장치에 할당된 IP 주소입니다..",
	"Checking Internet connectivity": "인터넷 연결 확인 중",
	"Detecting Internet connection": "인터넷 연결을 감지 중",
	"Choose this option if your Internet connection reguires a username and passowrd to get online. Most DSL modems use this connection type of connction.": "온라인 연결을 위해 사용자 이름과 비밀번호를 입력하는 인터넷 연결은 이 옵션을 선택하세요. 대부분의 DSL 모뎀은 이 연결 유형을 사용합니다.",
	"Some firmware upgrades reset the router's configuration options to the factory defaults.,": "일부 펌웨어 업그레이드 시 공유기의 설정이 공장 초기값으로 복구됩니다.",
	"On Schedule": "스케줄 적용",
	"The Schedule configuration option is used to manage schedule rules for various firewall and parental control features.": "스케줄 설정 옵션은 다양한 방화벽 설정 및 자녀보호 기능 관리에 사용됩니다.",
	"Authentication": "인증",
	"Auto(PAP+CHAP)": "자동 (PAP + CHAP)",
	"Autoconfiguration (SLAAC/DHCPv6)": "자동 구성(SLAAC/DHCPv6)",
	"Obtain IPV6 Servers automatically.": "IPV6 서버 자동 구성",
	"Automatic Time Confuguration": "자동 시간 설정",
	"Obtain a DNS server address automatically or enter a specific DNS server address.": "자동으로 DNS 서버 주소 받거나 특정 DNS 서버 주소를 입력하여 주십시오.",
	"Wrong password, please try again.": "잘못된 비밀번호입니다. 다시 시도하시기 바랍니다..",
	"Locked": "잠금",
	"Unlocked": "잠금 해제",
	"To access device management,click here.": "장치 관리에 접속하려면 여기를 클릭하십시오.",
	"DEVICE NAME SETUP": "장치명 설정",
	"The device is not connected to an uplink router, click &quot;Next&quot; to find available Wi-Fi networks.": "장치가 업링크 공유기에 연결되어 있지 않은 경우 &quot;다음&quot;을 클릭하여 사용 가능한 Wi-Fi 네트워크를 찾을 수 있습니다.",
	"Click on the": "클릭하여 주십시오.",
	"Choose a IPv4 provisioning mechanism to be used by the device.": "장치에서 사용되는 IPv4의 프로비저닝 메커니즘을 선택하여 주십시오.",
	"Choose a IPv6 provisioning mechanism to be used by the device.": "장치에서 사용되는 IPv6를 프로비저닝 메커니즘을 선택하여 주십시오.",
	"Device IP Address": "장치 IP 주소",
	"Please plug one end of the Ethernet cable included with your device into the port labeled INTERNET on your device. Plug the other end of this cable into the Ethernet port on yourDSL or cable broadband modem.": "이더넷 케이블의 한 쪽을 공유기 뒷면 인터넷 포트에 연결하고 다른 한 쪽을 DSL 또는 광대역 모뎀에 연결 후 모뎀의 전원을 껐다가 켜주시기 바랍니다.",
	"Rebooting....": "재부팅 중....",
	"Rebooting will disconnect any active internet sessions.": "재부팅되면 인터넷 ​​연결이 끊어집니다.",
	"Before Save mydlink, the Admin Password of DIR-508L can not be blank.": "mydlink 서비스를 사용하기 위해 반드시 관리자 비밀번호를 설정하시기 바랍니다.",
	"Sent": "전송",
	"Sent (TX)": "전송 (TX)",
	"The e-mail address and password combination is incorrect. Please try again.": "이메일 주소와 비밀번호 조합이 올바르지 않습니다. 다시 시도하여 주십시오.",
	"On Log Full": "Log-Full 일 때",
	"Static Network": "고정 네트워크",
	"Extender": "확장기기",
	"seconds": "초",
	"Second(s)": "초",
	"Seconds...": "초 ...",
	"Total Kbit(s)": "총 Kbit(s)",
	"Total Byte(s)": "총 바이트",
	"Using up to 32 characters": "최대 32 자까지 사용",
	"Append": "추가",
	"DENY computers access to ONLY these sites": "이 사이트만 접속 차단",
	"Computer Name": "컴퓨터 이름",
	"ALLOW computers access to ONLY these sites": "해이 사이트만 접속 허용",
	"Upload File": "파일 업로드",
	"Save Settings To File": "설정 파일 저장",
	"Restore Settings From File": "파일에서 설정 복구",
	"Please select a file": "파일을 선택하여 주십시오.",
	"Firmware Imformation": "펌웨어 정보",
	"Do not power off the router until the firmware upgrade is complete!": "펌웨어 업그레이드가 완료 될 때까지 공유기의 전원을 끄지 마십시오.",
	"Do not close the page or power off the service until the Firmware Upgrade is complete!": "펌웨어 업그레이드가 완료 될 때까지 공유기의 전원을 끄거나 페이지를 닫지 마십시오.",
	"Firmware Uploading": "펌웨어 업로드 중",
	"Port Forwarding is used to open ports in your router and to redirect traffic to those ports to a specific device on your network. This may be needed for specific applications, games, or services. You can enter individual ports (80, 68, 888), port ranges (100-150), or in a mixed format (1020-5000, 689).": "포트 포워딩은 공유기에서 포트를 열고 해당 포트에 대한 트래픽을 네트워크에 있는 특정 장치로 전달하는 기능으로 특정 어플리케이션, 게임, 서비스 사용 시 필요할 수 있습니다. 포트 번호는 개별 포트(80, 68, 888), 범위 포트(100-150), 개별 포트와 범위 포트가 혼합된 형식(1020-5000, 689)으로 입력할 수 있습니다.",
	"Create Folder": "폴더 생성",
	"Please enter a folder name": "폴더 이름을 입력하여 주십시오.",
	"Profile List": "프로필 목록",
	"Total": "합계",
	"Hotspot Network": "핫스팟 네트워크",
	"Hotspot Name (SSID)": "핫스팟 이름 (SSID)",
	"Hotspot Client": "핫스팟 클라이언트",
	"Always-on": "항상 켜짐",
	"This schedule cannot be deleted because it is being used by another feature.": "해당 스케줄 규칙이 다른 기능에 적용되어 있어 삭제할 수 없습니다.",
	"Please enter a matrix.": "경로 설정 값을 입력하여 주십시오.",
	"Mixed 802.11a and 802.11n": "802.11a and 802.11n 혼용",
	"Checking....,": "확인중 ....",
	"Give Your Extended Wi-Fi Network(SSID) a Name": "확장된 Wi-Fi 네트워크 이름(SSID) 지정",
	"Extended Wi-Fi Network Name": "확장된 Wi-Fi 네트워크 이름",
	"Extended Wi-Fi Network Name(SSID)": "확장된 Wi-Fi 네트워크 이름(SSID)",
	"Give Your Extended Wi-Fi Network a Password": "확장된 Wi-Fi 네트워크 비밀번호 지정",
	"Extended Wi-Fi": "확장된 Wi-Fi",
	"Extended Wi-Fi Password": "확장된 Wi-Fi 비밀번호",
	"PLEASE ENTER THE SETTINGS FOR THE EXTENDED NETWORK": "확장된 네트워크에 대한 설정을 입력하여 주십시오.",
	"Use the same Wi-Fi Network Name for the Extended Network.": "확장된 네트워크에 동일한 Wi-Fi 네트워크 이름(SSID)을 사용합니다.",
	"Wi-Fi 2.4GHZ": "Wi-Fi 2.4GHz",
	"Guest Zone 2.4GHZ": "게스트 존 2.4GHz",
	"Guest Zone 5GHZ": "게스트 존 5GHz",
	"Smart Connect": "스마트 연결",
	"Primary 5GHz": "기본 5GHz",
	"Secondary 5GHz": "보조 5GHz",
	"5GHz Low Band Guest Zone": "5Ghz 하위 채널 게스트 존",
	"5GHz High Band Guest Zone": "5Ghz 상위 채널 게스트 존",
	"5GHz Low Band Wi-Fi Name (SSID)": "5Ghz 하위채널 Wi-Fi 이름(SSID)",
	"5GHz High Band Wi-Fi Name (SSID)": "5Ghz 상위채널 Wi-Fi 이름(SSID)",
	"can't be broadcast address": "브로드캐스트 주소가 아닙니다.",
	"can't be network address": "네트워크 주소가 아닙니다.",
	"WAN Gateway IP address": "WAN 게이트웨이 IP 주소",
	"must be within the WAN subnet.": "WAN 서브넷은 반드시 같아야 합니다.",
	"SSID is required.": "SSID가 반드시 필요합니다.",
	"The SSID contains invalid characters. Please check it.": "SSID 입력이 올바르지 않습니다. 다시 확인하여 주십시오.",
	"The Wireless Security Password must be at least 8 characters long.": "Wi-Fi 보안 비밀번호는 반드시 8자리 이상으로 입력해야 합니다.",
	"The password should not have space at the beginning or the end.": "비밀번호 첫 글자와 마지막 글자에 공란(space)은 입력 할 수 없습니다.",
	"The WPA key must be exactly 8 hexadecimal digits long (0-9, A-F).": "WPA 비밀번호는 만드시 8자리 이상의 A-Z, 0-9 문자로 입력해야 합니다.",
	"Invalid WPA key. Please choose a WPA key containing exactly 8 hexadecimal characters.": "잘못 된 WPA 키입니다. WPA 키는 8자리 이상 입력해야 합니다.",
	"Congratulations, you are now connected to the Internet.": "축하합니다. 인터넷에 접속되었습니다.",
	"Complete Installation": "설치 완료",
	"CABLE DISCONNECTED FROM INTERNET PORT": "인터넷 포트에 케이블 연결이 끊어졌습니다.",
	"Please make sure the cable between the ADSL/cable modem and the router is properly connected.": "ADSL/케이블 모뎀과 공유기 사이에 연결된 케이블을 확인하여 주십시오.",
	"Please check that the hardware is properly connected and configured (refer to the Quick Installation Guide for details) and click \"Try Again\".": "하드웨어의 연결과 설정을 확인하고(빠른 설치 가이드 참고) \"다시 시도\"를 클릭하여 주십시오.",
	"PPPoE user name or password is incorrect.": "PPPoE 사용자명 또는 비밀번호가 맞지 않습니다.",
	"*User name and password are case-sensitive. Please ensure that Caps Lock is off, then click \"Previous\", re-enter the PPPoE user name and password, and click \"Connect\".": "사용자명과 비밀번호가 올바르지 않습니다. Caps Lock을 끄고, \"이전\" 버튼을 눌러  PPPoE 사용자명과 비밀번호를 다시 입력한 후 \"연결\" 버튼을 눌러 주시기 바랍니다.",
	"*Please check your Internet account information or contact your Internet service provider for your PPPoE details, then click \"Previous\", re-enter the PPPoE user name and password, and click \"Connect\".": "인터넷 계정 정보를 확인하거나 인터넷 서비스 제공자(ISP)에 문의하시기 바랍니다. \"이전\" 버튼을 눌러  PPPoE 사용자명과 비밀번호를 다시 입력한 후 \"연결\" 버튼을 눌러 주시기 바랍니다.",
	"CONNECTING TO THE INTERNET": "인터넷 연결 중",
	"The Router IP Address is belong to the lease pool of DHCP server.": "DHCP 범위에 공유기의 IP는 입력 할 수 없습니다.",
	"Bandwidth": "대역폭",
	"Policy":"정책"
}
