{

	"Home": "Главная страница",
	"Settings": "Настройки",
	"Management": "Управление",
	"Internet(WAN)": "Интернет",
	"Wireless(Wi-Fi)": "Беспроводная сеть",
	"Network(LAN)": "Сеть",
	"Wizard": "Мастер настройки",
	"SharePort": "SharePort",
	"mydlink": "mydlink",
	"Firewall Settings": "Межсетевой экран",
	"Virtual Server": "Виртуальный сервер",
	"Port Forwarding": "Перенаправление портов",
	"Website Filter": "Фильтр Web-сайтов",
	"Static Route": "Статический маршрут",
	"Disabled": "Выключено",
	"Enabled": "Включено",
	"Advanced": "Расширенные",
	"System Admin": "Системный Администратор",
	"COPYRIGHT": "COPYRIGHT &copy; 2015 D-Link",


	"There is unsaved data on this page. Do you want to abandon it?": "На странице есть несохраненные данные. Вы действительно хотите покинуть страницу?",
	"Remaining": "Оставшееся",
	"Not Available": "Недоступно",
	"Go to settings": "Перейти в настройки",
	"Click here for help.": "Для получения справки нажмите здесь.",
	"Type the characters you see in the picture below.": "Введите символы, изображенные ниже.",
	"Unsecured": "Не защищено",
	"<< Computer Name": "<< Имя компьютера",
	"<< Application Name": "<< Имя приложения",
	"Host": "Хозяин",
	"Guest": "Гость",


	"Model Name": "Название модели",
	"Hardware Version" : "Аппаратная версия",
	"Firmware Version" : "Версия ПО",
	"Language" : "Язык",
	"Admin Password": "Пароль администратора",
	"Log In" : "Войти",
	"To access your storage with SharePort Web Access," : "Чтобы получить доступ к хранилищу данных с помощью SharePort Web Access, ",
	"click here." : "нажмите здесь.",
	"Invalid password, please try again.": "Некорректный пароль, пожалуйста, попробуйте еще раз.",
	"Invalid password or captcha, please try again.": "Некорректный пароль или код CAPTCHA. Пожалуйста, попробуйте еще раз.",
	"The Private Browsing feature of Safari is incompatible with this device's interface. You will need to disable Private Browsing to log in.": "Необходимо выключить режим приватного просмотра, чтобы войти.",
	"License Agreement": "Лицензионное соглашение",
	"To access device management,": "Для доступа к управлению устройством, ",


	"Current Status": "Текущий статус",
	"Click on any item in the diagram for more information.": "Нажмите на любой элемент диаграммы для получения дополнительной информации.",
	"Setup Wizard": "Мастер настройки",
	"Router": "Маршрутизатор",
	"Internet": "Интернет",
	"NULL": "ЗНАЧЕНИЕ НЕИЗВЕСТНО",
	"LAN": "LAN",
	"WAN": "WAN",
	"Router IP Address": "IP-адрес маршрутизатора",
	"MAC Address": "MAC-адрес",
	"<< MAC Address": "<< MAC-адрес",
	"Wi-Fi 2.4GHz": "Wi-Fi 2.4 ГГц",
	"Wi-Fi 5GHz": "Wi-Fi 5 ГГц",
	"Guest Zone 2.4GHz": "Гостевая зона 2.4 ГГц",
	"Guest Zone 5GHz": "Гостевая зона 5 ГГц",
	"IP Address": "IP-адрес",
	"Subnet Mask": "Маска подсети",
	"Default Gateway": "Основной шлюз",
	"Available Space": "Доступный объем",
	"Total Space": "Общий объем",
	"Service Name": "Имя сервиса",
	"Ethernet Device": "Устройство Ethernet",
	"Wi-Fi Clients": "Wi-Fi клиенты",
	"USB Device": "USB-устройство",
	"USB Name": "Имя USB",
	"Status": "Статус",
	"Wi-Fi Name (SSID)": "Имя Wi-Fi (SSID)",
	"Password": "Пароль",
	"IPv6 Connection Type": "Тип соединения IPv6",
	"Primary IPv6 DNS Server": "Предпочитаемый IPv6-адрес DNS",
	"Secondary IPv6 DNS Address": "Альтернативный IPv6-адрес DNS",
	"LAN IPv6 Link-Local Address": "IPv6-адрес Link-Local LAN",
	"DHCP-PD": "DHCP-PD",
	"IPv6 Network Assigned by DHCP-PD": "Сеть IPv6, назначенная DHCP-PD",
	"LAN IPv6 Address": "IPv6-адрес LAN",
	"Guest Zone": "Гостевая зона",
	"Connection Type": "Тип соединения  ",
	"Network Status": "Статус сети",
	"Connection Uptime": "Время соединения",
	"Primary DNS Server": "Предпочитаемый DNS-сервер",
	"Secondary DNS Server": "Альтернативный DNS-сервер",
	"SharePort": "SharePort",
	"Release IP Address": "Сбросить IP-адрес",
	"Renew IP Address": "Обновить IP-адрес",
	"Disconnect": "Отключить",
	"Connect": "Подключить",
	"Ignore": "Отклонить",
	"Connected": "Подключено",
	"Connecting": "Выполняется подключение",
	"Disconnected": "Отключено",
	"DHCP": "Dynamic IP (DHCP)",
	"Static": "Static IP (Static)",
	"DHCPPPPoE": "Dynamic IP (PPPoE)",
	"StaticPPPoE": "Static IP (PPPoE)",
	"DynamicPPTP": "Dynamic IP (PPTP)",
	"StaticPPTP": "Static IP (PPTP)",
	"DynamicL2TP": "Dynamic IP (L2TP)",
	"StaticL2TP": "Static IP (L2TP)",
	"DsLite": "DS-Lite",
	"A new firmware is available! Do you want to download and upgrade the firmware?": "Доступно новое программное обеспечение! Хотите загрузить и обновить программное обеспечение?",
	"Your changes are being saved, and the device will need to reboot.": "Выполняется сохранение измененных настроек, потребуется перезагрузка устройства.",
	"Internet Connected": "Подключено к сети Интернет",
	"Internet Disconnected": "Отключено от сети Интернет",
	"New firmware available": "Доступно новое программное обеспечение",
	"Get Help": "Получить справку",
	"Connected Clients": "Подключенные клиенты",
	"Click on the pencil icon to give the device a name to make it easy to identify.": "Нажмите на значок с карандашом, чтобы дать устройству имя для более простой идентификации.",
	"You can block a device from accessing your network at all times or according to a schedule by using the Block dropdown box.": "Используйте раскрывающееся меню 'Заблокировать' для постоянной блокировки доступа устройства к сети или по расписанию.",
	"There are no devices available": "Нет доступных устройств",
	"IPv4 Network": "Сеть IPv4 ",
	"IPv6 Network": "Сеть IPv6",
	"Cable Status": "Состояние кабеля",
	"Click to repair":	"Нажмите для восстановления",
	"No USB device detected": "USB устройство не обнаружено",
	"Link-Local Address": "Локальный адрес",
	"Router IPv6 Address": "IPv6-адрес",
	"Assigned Prefix": "IPv6 префикс",
	"IPv6": "IPv6",
	"IPv4": "IPv4",
	"Limited Connection": "Ограниченное соединение",
	"Release": "Освободить",
	"Renew": "Обновить",
	"6rd": "6rd",
	"Parental Control": "Родительский контроль",


	"Welcome": "Добро пожаловать",
	"This wizard will guide you through a step-by-step process to configure your new D-Link device.": "Этот мастер поможет произвести пошаговую настройку Вашего устройства D-Link.",
	"Step 1: Install your device": "Шаг 1: Установите устройство",
	"Step 2: Configure your Network and Wi-Fi settings": "Шаг 2: Настройте параметры сети и Wi-Fi",
	"Step 3: Set your router password": "Шаг 3: Установите пароль маршрутизатора",
	"Step 4: Set up mydlink service": "Шаг 4: Установите сервис mydlink",
	"Your Device": "Ваше устройство",
	"Cable/xDSL Broadband Modem": "xDSL/Кабельный модем",
	"DHCP Connection (Dynamic IP Address)": "DHCP-соединение (Динамический IP-адрес)",
	"Choose this if your Internet connection automatically provides you with an IP Address. Most Cable Modems use this type of connection.": "Выберите этот тип соединения, если при использовании Интернет-соединения IP-адрес присваивается автоматически.",
	"Username/Password Connection (PPPoE)": "Имя пользователя/Пароль (PPPoE)",
	"Choose this option if your Internet connection reguires a username and passowrd to get online. Most DSL modems use this connection type of connection.": "Выберите этот тип соединения, если для установки Интернет-соединения требуются имя пользователя и пароль.",
	"Static IP Address Connection": "Соединение типа Статический IP",
	"Choose this option if your Internet Setup Provider provided you with IP Address information that has to be manually configured.": "Выберите этот тип соединения, если провайдер предоставил Вам фиксированный IP-адрес.",
	"Username": "Имя пользователя",
	"Gateway Address": "Адрес шлюза",
	"Primary DNS Address": "Предпочитаемый DNS-адрес",
	"Secondary DNS Address": "Альтернативный DNS-адрес",
	"2.4GHz Wi-Fi Network Name": "Имя сети Wi-Fi 2.4 ГГц",
	"5GHz Wi-Fi Network Name": "Имя сети Wi-Fi 5 ГГц",
	"The Wi-Fi Network Name is up to 32 characters. You will need to join your Wi-Fi network using this Network Name (SSID).": "В названии сети Wi-Fi должно быть использовано не более 32 символов. Это название (SSID) потребуется для подключения к Вашей сети Wi-Fi.",
	"Wi-Fi Password": "Пароль Wi-Fi",
	"2.4GHz Wi-Fi Password": "Пароль Wi-Fi 2.4 ГГц",
	"5GHz Wi-Fi Password": "Пароль Wi-Fi 5 ГГц",
	"The password must contain at least 8 characters. You will need to join your Wi-Fi network using this password.": "Пароль должен содержать не менее 8 символов.  Этот пароль потребуется для подключения к Вашей сети Wi-Fi.",
	"Device Admin Password": "Пароль администратора",
	"This device is mydlink-enabled, which allows you to remotely monitor and manage your network through the mydlink.com website, or through the mydlink mobile app.": "Это устройство поддерживает сервис mydlink, который обеспечивает возможность удаленного наблюдения и управления сетью через Web-сайт mydlink.com или с помощью мобильного приложения mydlink.",
	"You can register this device with your existing mydlink account. If you do not have one, you can create one now.": "Можно зарегистрировать это устройство с существующей учетной записью mydlink. Если учетная запись отсутствует, можно создать ее сейчас.",
	"Do you have an existing mydlink account?": "У Вас есть учетная запись mydlink?",
	"Yes, I have a mydlink account": "Да, у меня есть учетная запись mydlink.",
	"No, I want to create a new mydlink account": "Нет, я хочу создать новую учетную запись mydlink.",
	"E-mail Address (Account Name)": "Адрес электронной почты (Имя учетной записи)",
	"First Name": "Имя",
	"Last Name": "Фамилия",
	"I accept the mydlink": "Я принимаю <a href=\"https://www.mydlink.com/termsOfUse\"target=\"_blank\">условия соглашения mydlink.</a>",
	"Connect to the Wi-Fi network from your mobile device or PC": "Подключиться к сети Wi-Fi с помощью мобильного устройства или компьютера",
	"1.Please go to Settings > Wi-fi, and choose": "1. Пожалуйста, перейдите в Настройки > Wi-Fi и выберите",
	"from the list of Wi-Fi network services.": "из списка один из сервисов сети Wi-Fi.",
	"2.Enter the password you just setup when prompted.": "2. Введите пароль, который был задан.",
	"Wi-Fi Client": "Wi-Fi клиент",
	"Save": "Сохранить",
	"Please wait": "Пожалуйста, подождите",
	"Configure Your Internet Connection": "Настройте Интернет-соединение",
	"Detecting Internet Connection": "Определяется тип Интернет-соединения",
	"Install": "Установить",
	"Please plug one end of the Ethernet cable included with your device into the port labeled INTERNET on your device. Plug the other end of this cable into the Ethernet port on your DSL or cable broadband modem, and power cycle the modem.": "Пожалуйста, подключите входящий в комплект поставки Ethernet-кабель к порту INTERNET на устройстве и к порту Ethernet на DSL/кабельном модеме.",
	"Please select your Internet connection type below": "Пожалуйста, выберите ниже тип Интернет-соединения",
	"PPPoE": "PPPoE",
	"To setup this Internet connection, you will need to have a User Name from your Internet Service Provider. If you do not have this information, please contact your ISP.": "Чтобы установить данное Интернет-соединение, необходимо имя пользователя, полученное у провайдера. Если эта информация отсутствует, пожалуйста, обратитесь к провайдеру.",
	"Static IP": "Статический IP",
	"Dynamic IP (DHCP)": "Динамический IP (DHCP)",
	"To set up this conncetion you will need to have a complete list of IP information by your Internet Service Provider. If you have a Static IP connection and do not have this information, please contact your ISP.": "Для создания соединения типа Статический IP необходимо иметь информацию об IP-адресе, полученную от провайдера. Свяжитесь с провайдером, если данная информация отсутствует.",
	"Wi-Fi Settings": "Настройки Wi-Fi",
	"To setup a Wi-Fi Network you will need to give your Wi-Fi Network a Name(SSID) and Password.": "Чтобы установить сеть Wi-Fi, необходимо задать название (SSID) и пароль сети Wi-Fi.",
	"By default, your new D-Link device does not have a password configured for administrator access to the Web-based configuration utility. To secure your new device, please create a password below.": "По умолчанию новое устройство D-Link не имеет пароля для доступа на Web-интерфейсу. Чтобы защитить устройство, пожалуйста, задайте пароль ниже.",
	"Below is a summary of your Wi-Fi security and device password settings. Please make a note of your settings and click \"Next\".": "Ниже приводится краткая информация о настройках. Пожалуйста, учтите, ваши настройки и сохранить конфигурацию.",
	"Checking Your Internet Connectivity": "Проверка Вашего подключения к Интернет",
	"Checking Internet Connectivity": "Проверка подключения к Интернет",
	"mydlink Registration": "Регистрация в mydlink",
	"Congratulations": "Поздравляем",
	"Congratulations, your device has been configured. You can now connect to your Wi-Fi network by using the new Wi-Fi Network Name and Password you created.": "Поздравляем, устройство настроено. Теперь можно подключиться к сети Wi-Fi, используя заданные имя и пароль сети Wi-Fi.",
	"Back": "Назад",
	"Next": "Далее",
	"Skip": "Пропустить",
	"Finish": "Завершить",
	"Registered": "Зарегистрировано",
	"Unregistered": "Не зарегистрировано",
	"Summary": "Краткая информация",
	"Use the same password for both networks": "Используйте один и тот же пароль для обеих сетей",
	"Email or password field is required.": "Требуется ввести email или пароль.",


	"DHCP Renew": "Обновление DHCP",
	"DHCP Release": "Сброс DHCP",
	"You may now use mydlink service with this device.": "Теперь можно использовать службу mydlink с данным устройством",
	"2.4GHz Guest Zone": "Гостевая зона 2.4 ГГц",
	"5GHz Guest Zone": "Гостевая зона 5 ГГц",
	"Your changes are being saved, please wait...": "Выполняется сохранение настроек, пожалуйста, подождите...",
	"Wi-Fi": "Wi-Fi",
	"View": "Просмотр",
	"Desktop": "Настольный",
	"Mobile": "Мобильный",
	"Wi-Fi Name": "Имя Wi-Fi",
	"2.4GHz Wi-Fi Name": "Имя сети Wi-Fi 2.4 ГГц",
	"5GHz Wi-Fi Name": "Имя сети Wi-Fi 5 ГГц",


	"Wi-Fi Clients (Guest Zone)": "Wi-Fi клиенты (Гостевая зона)",
	"Click on a device to view more information about it, or click on the pencil icon to give the device a name to make it easy to identify. You can block a device from accessing your network always or according to a schedule by using the Block dropdown box.": "Нажмите на значок устройства для получения подробной информации о нем или нажмите на значок с карандашом, чтобы задать устройству имя для более удобной идентификации. Используйте раскрывающееся меню для ограничения доступа в интернет по расписанию.",
	"Here, you can see a list of all devices connected through Wi-Fi. Click on a device to view more information about it, or click on the pencil icon to give the device a name to make it easy to identify. You can block a device from accessing your network always or according to a schedule by using the Block dropdown box.": "Здесь можно увидеть список всех устройств, подключенных по Wi-Fi. Нажмите на значок устройства для получения подробной информации или нажмите на значок с карандашом, чтобы задать устройству имя для более удобной идентификации. Используйте раскрывающееся меню для ограничения доступа в интернет по расписанию.",
	"Vendor": "Производитель",
	"Reserve IP": "Зарезервировать IP-адрес",
	"Access": "Доступ",
	"Allowed": "Разрешен",
	"Blocked": "Заблокирован",
	"Your Wi-Fi network needs to be enabled in order to turn on Guest Zone network. Would you like to turn on both?": "Для активации сети гостевой зоны должна быть включена сеть Wi-Fi. Хотите включить обе функции?",
	"Here, you can see a list of all devices connected through an Ethernet cable. Click on a device to view more information about it, or click on the pencil icon to give the device a name to make it easy to identify. You can block a device from accessing your network always or according to a schedule by using the Block dropdown box.": "Здесь отображается список всех устройств, подключенных с помощью Ethernet-кабеля. Нажмите на устройство для получения подробной информации о нем или нажмите на значок с карандашом, чтобы дать устройству имя для упрощения его идентификации. Используйте раскрывающееся меню 'Заблокировать' для постоянной блокировки доступа устройства к сети или по расписанию.",


	"Use this section to configure your Internet Connection type. There are several connection types to choose from Static IP, DHCP, PPPoE, PPTP, L2TP, and DS-Lite. If you are unsure of your connection method, please contact your Internet Service Provider. Note:  If using the PPPoE option, you will need to remove or disable any PPPoE client software on your computers.": "Используйте этот раздел для настройки типа Интернет-соединения. Можно выбрать один из следующих типов соединения: Static IP, DHCP, PPPoE, PPTP, L2TP и DS-Lite. Если Вы не уверены, какой тип соединения используется, свяжитесь с Вашим провайдером. Примечание: если используется соединение PPPoE, требуется удалить или отключить все соединения PPPoE на компьютерах.",
	"My Internet Connection is": "Тип Интернет-соединения",
	"Host Name": "Имя хоста",
	"Mac Address Clone": "Клонировать MAC-адрес",
	"PPTP IP Address": "IP-адрес PPTP",
	"PPTP Server IP Address": "IP-адрес сервера PPTP",
	"PPTP Subnet Mask": "Маска подсети PPTP",
	"PPTP Gateway IP Address": "IP-адрес шлюза PPTP",
	"L2TP IP Address": "IP-адрес L2TP",
	"L2TP Server IP Address": "IP-адрес сервера L2TP",
	"L2TP Subnet Mask": "Маска подсети L2TP",
	"L2TP Gateway IP Address": "IP-адрес шлюза L2TP",
	"MTU": "MTU",
	"Address Mode": "Режим адресации",
	"Reconnect Mode": "Режим повторного подключения",
	"Maximum Idle Time": "Максимальное время простоя",
	"DS-Lite Configuration": "Настройка DS-Lite",
	"DS-Lite DHCPv6 Option": "Опция DHCPv6 DS-Lite",
	"Manual Configuration": "Ручная настройка",
	"AFTR IPv6 Address": "IPv6-адрес AFTR",
	"B4 IPv4 Address": "IPv4-адрес B4",
	"WAN IPv6 Address": "IPv6-адрес WAN",
	"IPv6 WAN Default Gateway": "Основной шлюз IPv6 WAN",
	"Advanced Settings": "Расширенные настройки",
	"Manual": "Вручную",
	"Always on": "Всегда",
	"On demand": "По требованию",
	"Dynamic IP": "Динамический IP-адрес",
	"The MTU value should be 1280 ~ 1460.": "Это значение должно находиться в диапазоне от 1280 до 1460.",
	"The MTU value should be 1280 ~ 1492.": "Это значение должно находиться в диапазоне от 1280 до 1492.",
	"The MTU value should be 1280 ~ 1500.": "Это значение должно находиться в диапазоне от 1280 до 1500.",
	"IPv6 PPPoE is share with IPv4 PPPoE. Please change IPv6 WAN protocol to PPPoE at first.": "IPv6 PPPoE используется совместно с IPv4 PPPoE. Пожалуйста, сначала измените протокол WAN IPv6 на PPPoE.",
	"Please choose one IPv6 connection type besides Link-Local Only, 6to4, 6rd, and IPv6 in IPv4 Tunnel !": "Пожалуйста, выберите один тип соединения IPv6 помимо Link-Local Only, 6to4, 6rd и IPv6 in IPv4 Tunnel!",
	"The default gateway should be in the same network.": "Основной шлюз должен находиться в той же сети.",
	"The dns server cannot be equal to the IP address.": "DNS-сервер не должен совпадать с IP-адресом.",
	"The router would not support the subnet mask which length is less than Class A.": "Маршрутизатор не будет поддерживать маску подсети, размер которой меньше подсети класса A.",
	"Please enter a primary dns server": "Пожалуйста, введите предпочитаемый DNS-сервер.",
	"Secondary DNS server should not be the same as Primary DNS server.": "Альтернативный DNS-сервер не должен совпадать с предпочитаемым DNS-сервером.",
	"The network id is the same with LAN.": "Идентификатор сети совпадает с LAN.",
	"IP or Domain name": "IP-адрес или доменное имя",
	"PPTP Server IP Address": "IP-адрес PPTP-сервера  ",
	"L2TP Server IP Address": "IP-адрес L2TP-сервера",
	"WAN Physical Settings": "Физические настройки WAN",


	"All of your IPv6 Internet and network connection details are displayed on this page.": "Вся подробная информация о Интернет-соединении IPv6 отображена на этой странице.",
	"Auto Detection": "Автоматическое определение",
	"Static IPv6": "Статический IPv6",
	"Auto Configuration (SLAAC/DHCPv6)": "Автоматическая настройка (SLAAC/DHCPv6)",
	"IPv6 in IPv4 Tunnel": "Туннель IPv6 в IPv4",
	"6to4": "6to4",
	"Local Connectivity Only": "Только возможность локального подключения",
	"Use Link-Local Address": "Использовать адрес Link-Local",
	"Subnet Prefix Length": "Длина префикса подсети",
	"PPPoE Session": "Сессия PPPoE",
	"Remote IPv4 Address": "Удаленный IPv4-адрес",
	"Remote IPv6 Address": "Удаленный IPv6-адрес",
	"Local IPv4 Address": "Локальный IPv4-адрес",
	"Local IPv6 Address": "Локальный IPv6-адрес",
	"6to4 Address": "Адрес 6to4",
	"6to4 Relay": "6to4 Relay",
	"Assign IPv6 Prefix": "Назначить префикс IPv6",
	"LAN IPv6 Link-Local Address": "IPv6-адрес Link-Local LAN",
	"IPv6 DNS SETTINGS": "НАСТРОЙКИ DNS IPv6",
	"LAN IPv6 ADDRESS SETTINGS": "НАСТРОЙКИ IPv6-АДРЕСА LAN",
	"LAN IPv6 Address": "IPv6-адрес LAN",
	"ADDRESS AUTOCONFIGURATION SETTINGS": "ПАРАМЕТРЫ АВТОНАСТРОЙКИ АДРЕСА",
	"Enable Automatic IPv6 Address Assignment": "Включить автоматическое назначение IPv6-адресов",
	"Enable Automatic DHCP-PD in LAN": "Включить автоматический DHCP-PD в LAN",
	"Autoconfiguration Type": "Тип автонастройки",
	"Enable DHCP-PD": "Включить DHCP-PD",
	"6RD MANUAL CONFIGURATION": "РУЧНАЯ НАСТРОЙКА 6rd",
	"Enable Hub and Spoke Mode": "Включить режим Hub and Spoke",
	"6rd Configuration": "Настройка 6rd",
	"6rd IPv6 Prefix": "Префикс IPv6 6rd",
	"6rd Border Relay IPv4 Address": "Border Relay IPv4-адрес 6rd",
	"IPv6 ULA SETTINGS": "Настройки IPv6 ULA",
	"Enable ULA": "Включить ULA",
	"Use Default ULA Prefix": "Использовать префикс ULA по умолчанию",
	"ULA Prefix": "Префикс ULA",
	"CURRENT IPv6 ULA SETTINGS": "ТЕКУЩИЕ НАСТРОЙКИ IPv6 ULA",
	"Current ULA Prefix": "Текущий префикс ULA",
	"LAN IPv6 ULA": "LAN IPv6 ULA",
	"minutes": "минуты",
	"DNS Type": "Тип DNS",
	"Obtain a DNS server address automatically": "Получить адрес DNS-сервера автоматически",
	"Use the following DNS address": "Использовать следующий DNS-адрес",
	"SLAAC+Stateless DHCP": "SLAAC + DHCP без сохранения состояния",
	"Stateful DHCPv6": "DHCPv6 с сохранением состояния",
	"6rd DHCPv4 Option": "Опция DHCPv4 6rd",
	"Share with IPv4": "Совместно использовать с IPv4",
	"Create a new session": "Создать новую сессию",
	"bytes": "байт",
	"Router Advertisement Lifetime": "Время жизни информационного сообщения от маршрутизатора ",
	"IPv6 Address Range (Start)": "Диапазон IPv6-адресов (Начальный IPv6)",
	"IPv6 Address Range (End)": "Диапазон IPv6-адресов (Конечный IPv6)",
	"IPv6 Address Lifetime": "Время жизни IPv6-адреса",
	"WAN IPv4 Address": "IPv4-адрес WAN",


	"coexistence": "Функция HT20/40 Coexistence",
	"Security Mode": "Режим безопасности",
	"None": "Нет",
	"WPA/WPA2-Personal": "WPA/WPA2-Personal",
	"Auto": "Автоматический",
	"High": "Высокий",
	"Low": "Низкий",
	"802.11 Mode": "Режим 802.11",
	"Wi-Fi Channel": "Канал Wi-Fi",
	"Transmission Power": "Мощность передатчика",
	"Channel Width": "Ширина канала",
	"Visibility Status": "Статус видимости",
	"Visible": "Видимый",
	"Invisible": "Невидимый",
	"Mixed 802.11b/g": "Mixed 802.11b/g",
	"Mixed 802.11g/n": "Mixed 802.11g/n",
	"Mixed 802.11b/g/n": "Mixed 802.11b/g/n",
	"Auto 20/40 MHz": "Auto 20/40 МГц",
	"Auto 20/40/80 MHz": "Auto 20/40/80 МГц",
	"Use this section to configure the wireless settings for your D-Link Router. Please note that changes made on this section may also need to be duplicated on your Wireless Client.": "Используйте данный раздел, чтобы настроить параметры беспроводной сети для маршрутизатора D-Link. Пожалуйста, помните, что настройки, измененные в данном разделе, также должны быть изменены на беспроводном клиенте.",
	"This page lets you configure a Wi-Fi Guest Zone. Wi-Fi Guest Zones are Wi-Fi networks that are separate from your normal ones, and use different Wi-Fi Network Names and passwords. Users connected to a Guest Zone cannot communicate or detect devices on your normal network unless the Routing Between Zones option is enabled. Guest Zones are useful to give guests Internet access without allowing them to access your own devices on your network.": "На этой странице настраивается гостевая зона Wi-Fi. Гостевая зона Wi-Fi - это сеть Wi-Fi, которая отделена от обычной сети. Гостевая зона полезна в том случае, когда пользователям требуется предоставить доступ к Интернет, в то же время запретив им доступ к Вашим устройствам в сети.",
	"Internet Access Only": "Только доступ к Интернет",
	"Home Network Access": "Маршрутизация между зонами",
	"Your changes are being saved. When reconnecting to this device, please use the new Wi-Fi name and password you created.": "При повторном подключении к данному устройству, пожалуйста, используйте новое название и пароль беспроводной сети.",
	"Your changes are being saved.": "Выполняется сохранение измененных настроек.",
	"Mixed 802.11a/n": "Mixed 802.11a/n",
	"Mixed 802.11n/ac": "Mixed 802.11n/ac",
	"Mixed 802.11a/n/ac": "Mixed 802.11a/n/ac",
	"802.11b only": "802.11b only",
	"802.11g only": "802.11g only",
	"802.11n only": "802.11n only",
	"802.11a only": "802.11a only",
	"802.11ac only": "802.11ac only",
	"Please select a wireless station.": "Пожалуйста, выберите беспроводную станцию.",
	"Station": "Станция",
	"Wireless Network Name": "Имя беспроводной сети",
	"Security": "Безопасность",
	"Scan": "Сканирование",
	"Password Length": "Длина пароля",
	"WI-FI PROTECTED SETUP": "Wi-Fi Protected Setup",
	"WPS status": "Статус WPS",
	"Device PIN": "PIN-код устройства",
	"Generate New PIN": "Генерировать новый PIN-код",
	"Save Device PIN": "Сохранить PIN-код устройства",
	"Reset to Unconfigured": "Сбросить конфигурацию",
	"PBC": "Метод PBC",
	"PBC Start": "Запуск PBC",
	"PIN": "PIN",
	"PIN Start": "Запуск PIN",
	"Scanning...": "Сканирование…",
	"Available hotspot networks": "Доступные сети hotspot",
	"WPA-Personal": "WPA-Personal",
	"Select": "Выбрать",
	"WEP password length is 10 or 26, password type must be Hexadecimal.": "Длина пароля WEP должна составлять 10 или 26 шестнадцатеричных символов.",
	"Your password must be 5 or 10 or 13 or 26 length.": "Длина пароля должна составлять 5, 10, 13 или 26 символов.",
	"WPA password length is 64, password type must be Hexadecimal.": "Длина пароля WPA должна составлять 64 шестнадцатеричных символа.",
	"Please enter a value between 0 and FF.": "Пожалуйста, введите значение от 0 до FF.",
	"Your password must be 5 or 10 characters length.": "Длина пароля должна составлять 5 или 10 символов.",
	"Your password must be 13 or 26 characters length.": "Длина пароля должна составлять 13 или 26 символов.",



	"Network": "Сеть",
	"Network Settings": "Настройки сети",
	"DHCP Server": "DHCP-сервер",
	"Use this section to configure the network settings for your device. You can enter a name for your device in the management link field, and use the link to access web UI  in a web browser. Recommend to change the management link if there are more than one D-Link devices within the network.": "Используйте эту страницу, чтобы настроить параметры локальной сети для маршрутизатора. Вы можете ввести имя или IP-адрес, используемые для доступа на web-интерфейс. Мы рекомендуем изменить IP-адрес, если в сети используется несколько устройств компании D-Link.",
	"LAN IP Address": "IP-адрес LAN",
	"Device Name": "Имя устройства",
	"Local Domain Name": "Имя локального домена",
	"Enable DNS Relay": "Включить DNS Relay",
	"DHCP IP Address Range": "Диапазон IP-адресов DHCP",
	"DHCP Lease Time": "Время аренды DHCP",
	"Always Broadcast": "Постоянная широковещательная передача",
	"compatibility for some DHCP Clients": "(совместимость для некоторых DHCP-клиентов)",
	"If you changed the IP address of the router you will need to change the IP address in your browser before accessing the configuration website again.": "Если IP-адрес маршрутизатора был изменен, необходимо изменить IP-адрес в браузере перед тем, как снова получить доступ к Web-интерфейсу.",
	"The new settings have been saved.": "Новая конфигурация сохранена успешно.",
	"to": "до",
	"Management Link": "Управляющее соединение",


	"Advanced Network": "Расширенные настройки сети",
	"Advanced Network settings allow you to configure some of the more advanced features of your router. It is recommended that you only change these settings if you are  familiar with them, or if you are specifically instructed to do so.": "Расширенные настройки сети позволяют настроить некоторые дополнительные функции маршрутизатора. Рекомендуется изменять эти настройки только в том случае, если Вы ознакомлены с их назначением и инструкцией.",
	"UPnP": "UPnP",
	"WAN Port Speed": "Скорость на WAN-порте",
	"IPv4 Multicast Streams": "Многоадресные потоки IPv4",
	"IPv6 Multicast Streams": "Многоадресные потоки IPv6",
	"Auto (10/100/1000 Mbps)": "Автоматически (10/100/1000 Мбит/с)",


	"SharePort": "SharePort",
	"SharePort allows you to share photos, music, movies and files simply by connecting a USB drive to your router. Access your files locally and remotely using the free mydlink SharePort app for your iOS or Android devices, or access them on a computer through the SharePort Web Access. The built-in Digital Living Network Alliance (DLNA) media server allows you to stream multimedia content to any DLNA compliant devices such as smart TVs and games consoles.": "SharePort позволяет совместно использовать фотографии, музыку, видео и другие файлы благодаря простому подключению USB-накопителя к маршрутизатору. Можно получить локальный или удаленный доступ к файлам, используя бесплатное приложение mydlink SharePort для устройств с iOS или Android, или получить доступ к ним на компьютере через SharePort Web Access. Встроенный медиа-сервер Digital Living Network Alliance (DLNA) обеспечивает передачу потокового медиа-контента на любые устройства с поддержкой DLNA, например Smart TV и игровые консоли.",
	"DLNA Media Server Configuration": "Настройка DLNA медиа-сервера",
	"DLNA Media Server": "DLNA медиа-сервер",
	"Web File Access": "Web-доступ к файлам",
	"Remote Access Port": "Порт удаленного доступа",
	"Remote HTTPS Port": "Порт удаленного HTTPS",
	"Enable Storage Remote Access": "Включить удаленный доступ HTTP к хранилищу данных",
	"Direct Links": "Прямые ссылки",
	"Local Access": "Локальный доступ",
	"SharePort Web Access": "Web-доступ SharePort",
	"Windows File Sharing (SAMBA)": "Совместное использование файлов (SAMBA)",
	"Windows File Sharing": "Совместное использование файлов ",
	"Require router's admin password": "Требуется пароль администратора",
	"Allow all users to access (No password)": "Разрешить доступ всем пользователям (Без пароля)",

	"UPnP Media Server": "UPnP Media Server",
	"The built-in UPnP media server streams music, videos, and photos stored on an attached USB drive to PCs, smartphones, tablets, smart TVs, or other media devices on your network. Web File Access allows you to access files on an attached USB drive through a web browser.": "Встроенный медиа-сервер UPnP воспроизводит потоковое видео, музыку и фотографии, хранящиеся на подключенном USB-накопителе, на компьютерах, смартфонах, планшетных компьютерах, smart TV и других медиа-устройствах в сети. Web-доступ к файлам позволяет использовать Web-браузер для доступа к файлам, хранящимся на подключенном USB-накопителе.",


	"\"Create User\" manage access to your storage devices or use the Guest account (guest/guest) to access the Guest Folder. After plugging in an SD card or USB storage drive, the new device will appear in the list with a link to it. You can then use this link to connect the drive and login with a user account.": "Создайте пользователя для управления доступом к устройствам хранения данных или используйте учетную запись гостя (guest/guest) для доступа к гостевой папке. После установки SD-карты или USB-накопителя новое устройство появится в списке со ссылкой на него. Затем можно использовать данную ссылку для подключения к накопителю и входа под учетной записью пользователя.",
	"Remote Access": "Удаленный доступ",
	"Create User": "Создать пользователя",
	"User Name": "Имя пользователя",
	"Access Path": "Путь доступа",
	"Permission": "Права доступа",
	"Edit": "Редактировать",
	"Delete": "Удалить",
	"Browse": "Обзор",
	"Apply": "Применить",
	"Create User": "Создать пользователя",
	"Create New User": "Создать нового пользователя",
	"Edit User Profile": "Редактировать профиль пользователя",
	"Folder": "Папка",
	"Select Folder": "Выбрать папку",
	"USB Device Name": "Имя USB-устройства",
	"Number of Device": "Номер устройства",
	"Read/Write": "Чтение/Запись",
	"Read Only": "Только чтение",
	"root": "корневая папка",
	"USB Port": "USB порт",
	"Disk Name": "Имя диска",


	"Creating a mydlink account and registering your router with mydlink will allow you to remotely montior and manage your network on your smartphone or tablet, as well as through the secure web portal. It also allows you to plug in a USB drive and access the stored files from anywhere in the world through iOS and Android apps as well as the web browser on your computer.": "Регистрация и настройка маршрутизатора в mydlink позволит воспользоваться функциями \"облачного\" сервиса mydlink, включая доступ и управление маршрутизатором в режиме онлайн через Web-сайт mydlink.",
	"mydlink Registration": "Регистрация в mydlink",
	"Sign Up": "Зарегистрироваться",
	"Sign In": "Войти",
	"Please enter your e-mail address and mydlink password.": "Пожалуйста, введите адрес электронной почты и пароль mydlink.",
	"You must accept the terms and conditions to continue.": "Необходимо принять условия соглашения, чтобы продолжить.",
	"mydlink Account": "Учетная запись в mydlink ",
	"mydlink Service": "Служба mydlink",


	"QoS Engine": "QoS Engine",
	"Connected clients can be assigned Internet access priority. Click and drag client cards into open slots.": "QoS приоритезирует сетевой трафик. Таким образом, можно определить, какие из устройств будут иметь больший приоритет. Например, можно задать компьютеру, скачивающему файлы, более низкий приоритет, чем ноутбуку, воспроизводящему потоковое видео, для того, чтобы скачиваемые файлы не занимали всю полосу пропускания, и потоковое видео воспроизводилось без задержек.",
	"Drag the device cards above to the Priority boxes below.": "Поместите значки устройств на поля приоритетов.",
	"Highest": "Наивысший",
	"Medium": "Средний",


	"Firewall": "Межсетевой экран",
	"Your router's high-performance firewall feature continuously monitors Internet traffic, protecting your network and connected devices from malicious Internet attacks.": "Здесь можно настроить различные функции межсетевого экрана, чтобы защитить сеть от атак. Нажмите на кнопки DMZ, Правила IPv4 и Правила IPv6, чтобы отобразить настройки для выбранной функции.",
	"Application Level Gateway (ALG) Configuration": "Настройка Application Level Gateway (ALG)",
	"Enable SPI IPv4": "Включить SPI IPv4",
	"Enable Anti-spoof Checking": "Включить анти-спуф проверку",
	"IPv6 Simple Security": "Простая защита IPv6",
	"IPv6 Ingress Filtering": "Включить фильтрацию входящего трафика IPv6",
	"PPTP": "PPTP",
	"IPSec (VPN)": "IPSec (VPN)",
	"RTSP": "RTSP",
	"SIP": "SIP",
	"IPv4 Rules": "Правила IPv4",
	"IPv6 Rules": "Правила IPv6",
	"Enable DMZ Host": "Включить DMZ-хост",
	"DMZ IP Address": "IP-адрес DMZ",


	"The IPv4 rule section is an advance feature used to deny or allow traffic from passing through the device.": "Раздел правил IPv4 является дополнительной функцией, используемой для того, чтобы запретить или разрешить прохождение трафика через устройство.",
	"Your router's built-in firewall also supports IPv6. Some applications or clients may require special adjustment for better performance or extra protection.": "Встроенный фаервол также поддерживает IPv6. Некоторые приложения или клиенты могут потребовать особых настроек для увеличения производительности или для дополнительной защиты.",
	"Any": "ANY",
	"Add Rule": "Добавить правила",
	"Name": "Имя",
	"Schedule": "Расписание",
	"Source IP Address Range": "Источник диапазона IP-адресов",
	"Destination IP Address Range": "Назначение диапазона IP-адресов",
	"Port Range": "Диапазон портов",
	"Turn IPv4 Filtering OFF": "ВЫКЛЮЧИТЬ фильтрацию IPv4",
	"Turn IPv4 Filtering ON and ALLOW rules listed": "ВКЛЮЧИТЬ фильтрацию IPv4 и РАЗРЕШИТЬ перечисленные правила",
	"Turn IPv4 Filtering ON and DENY rules listed": "ВКЛЮЧИТЬ фильтрацию IPv4 и ЗАПРЕТИТЬ перечисленные правила",
	"Turn IPv6 Filtering OFF": "ВЫКЛЮЧИТЬ фильтрацию IPv6",
	"Turn IPv6 Filtering ON and ALLOW rules listed": "ВКЛЮЧИТЬ фильтрацию IPv6 и РАЗРЕШИТЬ перечисленные правила",
	"Turn IPv6 Filtering ON and DENY rules listed": "ВКЛЮЧИТЬ фильтрацию IPv6 и ЗАПРЕТИТЬ перечисленные правила",
	"Create New Rule": "Создать новое правило",
	"Create New Route": "Создать новый маршрут",
	"Edit Rule": "Редактировать правило",
	"Edit Route": "Редактировать маршрут",


	"Your router helps share a single IP address assigned by your ISP among several clients in your home. Port forwarding allows traffic requests from a specified application to be directed to a specified client inside.": "Перенаправление портов используется для того, чтобы открыть порты на маршрутизаторе и перенаправить трафик на эти порты на определенное устройство в сети. Это может потребоваться для определенных приложений, игр или сервисов. Можно вводить отдельные порты (80, 68, 888), диапазон портов (100-150) или использовать смешанный формат (1020-5000, 689).",
	"Local IP": "Локальный IP-адрес",
	"TCP Port": "TCP-порт",
	"UDP Port": "UDP-порт",


	"Your router helps share a single IP address assigned by your Internet service provider among several clients in your home. Virtual servers are preset port mappings for popular services, like a web or e-mail server, that route traffic to a specified client inside.": "Виртуальный сервер позволяет задать один публичный порт на маршрутизаторе для перенаправления на внутренний IP-адрес LAN и приватный LAN-порт, если требуется. Эта функция полезна для размещения онлайн-сервисов, таких как FTP или Web-серверы.",
	"Protocol": "Протокол",
	"External Port": "Внешний порт",
	"Internal Port": "Внутренний порт",
	"Protocol Number": "Номер протокола",
	"Both": "Оба",
	"Other": "Другой",


	"The website filters feature allows rules to be set that restrict access to a specified web address (URL) or blocks specified keywords in the URL. You can use Website Filter to restrict access to potentially harmful and inappropriate websites.": "Фильтр Web-сайтов позволяет установить список Web-сайтов, посещение которых требуется разрешить или запретить. Можно использовать фильтр Web-сайтов для ограничения доступа к вредоносным и опасным сайтам.",
	"DENY clients access to ONLY these sites": "Запретить доступ к только этим сайтов",
	"ALLOW clients access to ONLY these sites": "Разрешить доступ только к этим сайтов",
	"Website URL/Domain": "URL-адрес Web-сайта/Домен",


	"Static Routes": "Статические маршруты",
	"Once connected to the Internet, your router automatically builds routing tables that determine where traffic should be sent. Static routes can override this process, allowing traffic to be directed to a specific client or location.": "На этой странице можно задать пользовательские маршруты, определяющие, каким образом данные будут перемещаться по сети.",
	"Destination Network": "Сеть назначения",
	"Mask": "Маска",
	"Gateway": "Шлюз",
	"Metric": "Матрица",
	"Interface": "Интерфейс",
	"DestNetwork": "Сеть назначения",
	"PrefixLen": "Длина префикса",
	"Add Route": "Добавить маршрут",
	"This page allows you to define custom routes to define how data traffic is moved around your network": "Эта страница позволяет назначить маршруты, чтобы определить, как трафик данных перемещается в вашей сети",


   	"Dynamic Domain Name Service allows your router to associate an easy-to-remember domain name such as [YourDomainName].com with the regularly changing IP address assigned by your Internet Service provider. This feature is helpful when running a virtual server.": "Dynamic DNS позволяет использовать удобное доменное имя, например, www.[YourDomainName].com, чтобы попасть на IP-адрес, присваиваемый маршрутизатору динамически. Эта функция полезна при размещении Web, FTP или игрового сервера и позволяет достичь сервера независимо от того, какой IP-адрес он имеет в настоящий момент.",
	"Server Address": "Адрес сервера",
	"Dynamic DNS": "Dynamic DNS",
	"Enable Dynamic DNS": "Включить Dynamic DNS",
	"Select Server Name": "Выбрать имя сервера",
	"Time Out": "Time Out",
	"IPv6 Address": "IPv6-адрес",
	"hours": "часы",
	"Add Record": "Добавить запись",
	"Create New Record": "Создать новую запись",
	"Edit Record": "Редактировать запись",


	"Time & Schedule": "Время и расписание",
	"Time": "Время",
	"Time Configuration": "Настройка времени",
	"Automatic Time Configuration": "Автоматическая настройка времени",
	"Manual Time Configuration": "Ручная настройка времени",
	"Date": "Дата",
	"Your router's internal clock is used for data logging and schedules for features. The date and time can be synchronized with a public time server on the Internet, or set manually.": "На этой странице можно настроить системные часы маршрутизатора. Можно установить время вручную или автоматически через сервер времени.",
	"System Time": "Системное время",
	"Time Zone": "Часовой пояс",
	"Enable Daylight Saving": "Включить переход на летнее время",
	"Update Time Using an NTP Server": "Обновить время, используя NTP-сервер",
	"Year/ Month/ Day": "(Год/ Месяц/ День)",
	"Hour/ Minute": "(Час/ Минута)",
	"Day": "День",
	"Hour": "Час",
	"Min": "Мин.",
	"Sec": "Сек.",
	"D-Link NTP Server": "NTP-сервер D-Link",
	"NTP Server": "NTP-сервер",


	"Some features, such as the firewall and website filters, can be turned on or off based on a schedule. One common use of schedules is to control access to the Internet by a specified device during specified time periods.": "Некоторые функции, такие как межсетевой экран и фильтры Web-сайтов, могут быть включены или выключены по расписанию. Расписания применяются для того, чтобы контролировать доступ определенного устройства к Интернет в заданные периоды времени.",
	"Monday": "Пн",
	"Tuesday": "Вт",
	"Wednesday": "Ср",
	"Thursday": "Чт",
	"Friday": "Пт",
	"Saturday": "Сб",
	"Sunday": "Вс",
	"All Day": "24 часа",
	"All Week": "7 дней в неделю",
	"Always": "Всегда включено",
	"Name": "название",
	"Schedule cannot be null!": "Расписание не может быть нулевым!",
	"Always OFF": "Always OFF",


	"System Log": "Системный журнал Syslog",
	"SysLog Settings": "Настройки сервера Syslog",
	"On-board diagnostics run continually in the background to monitor the health of your router. The results are recorded in the system log if it is enabled. This info can be used to diagnose common problems or help Customer Support resolve issues more quickly.": "Диагностика непрерывно мониторит состояние роутера. Результаты записываются в журнал событий. Эта информация необходима для решения проблем, возникающих в работе роутера.",
	"SysLog Server IP Address": "IP-адрес сервера Syslog",
	"Enable Logging to Syslog Server": "Включить запись журнала на сервере Syslog",
	"E-mail Settings": "Настройки электронной почты",
	"E-mail Log When Full or On Schedule": "Отправить журнал по электронной почте, когда он заполнен, или по расписанию",
	"Enable E-mail Notification": "Включить уведомление по электронной почте",
	"From E-mail Address": "С адреса электронной почты",
	"To E-mail Address": "На адрес электронной почты",
	"SMTP Server Address": "На адрес SMTP-сервера",
	"SMTP Server Port": "Порт SMTP-сервера",
	"Enable Authentication": "Включить аутентификацию",
	"Account Name": "Имя учетной записи",
	"Send When Log Full": "Отправить, когда заполнен журнал",
	"Send on Schedule": "Отправить по расписанию",


	"System": "Система",
	"Save Configuration": "Сохранить конфигурацию",
	"Restore Configuration From File": "Восстановить конфигурацию из файла",
	"Restore Factory Default": "Восстановить заводские настройки",
	"Reboot": "Перезагрузить",
	"This page lets you save your router's current settings to a file, restore your settings from a file, restore your router to factory default settings, or reboot the device. Please note that restoring the settings to the factory defaults will erase all settings, including any rules you have created.": "На этой странице можно сохранить текущие настройки маршрутизатора в файл, восстановить настройки из файла, восстановить заводские настройки маршрутизатора или перезагрузить устройство. Пожалуйста, помните, что восстановление заводских настроек удалит все настройки, включая созданные правила.",
	"Save Settings To Local Hard Drive": "Сохранить настройки на локальный диск",
	"Load Settings From Local Hard Drive": "Загрузить настройки с локального диска",
	"Restore To Factory Default Settings": "Восстановить в заводские настройки",
	"Reboot The Device": "Перезагрузить устройство",
	"Cancel": "Отмена",
	"Are you sure you want to restore configuration file?": "Уверены, что хотите восстановить конфигурационный файл?",
	"Do not close the page or power off the service until the restore configuration file is complete!": "Не закрывайте страницу и не выключайте устройство до завершения процесса восстановления конфигурационного файла!",
	"Restore configuration file failed!": "Ошибка восстановления конфигурационного файла!",
	"Restore configuration file success!": "Конфигурационный файл успешно восстановлен!",
	"Rebooting": "Выполняется перезагрузка",
	"Reboot success!": "Перезагрузка выполнена успешно!",
	"Are you sure you want to reset the device to its factory default settings? This will cause current settings to be lost.": "Уверены, что хотите сбросить устройство к заводским настройкам? Текущие настройки будут утеряны.",
	"Restore to factory default success!": "Заводские настройки успешно восстановлены!",
	"Select File": "Выбрать файл",
	"Restore": "Восстановить",
	"Restore Factory Default": "Восстановить заводские настройки",
	"Are you sure you want to restart the device?": "Вы действительно хотите перезагрузить устройство?",
	"OK": "OK",


	"Admin": "Администратор",
	"Admin Password": "Пароль администратора",
	"Administration": "Администрирование",
	"Use HTTPS": "Использовать HTTPS",
	"The admin account can change all router settings. To keep your router secure, you should give the admin account a strong password.": "Администратор обладает правами чтения/записи и может изменять пароли, тогда как пользователь имеет только права чтения. По умолчанию заданный пароль отсутствует. Настоятельно рекомендуется создать пароль, чтобы обезопасить маршрутизатор.",
	"Enable Graphical Authentication (CAPTCHA)": "Включить графическую аутентификацию (CAPTCHA)",
	"Enable HTTPS Server": "Включить HTTPS-сервер",
	"Enable Remote Management": "Включить удаленное управление",
	"Remote Admin Port": "Порт удаленного администрирования",
	"Remote Admin Inbound Filter": "Фильтр входящего трафика удаленного администрирования",


	"Upgrade Firmware": "Обновить программное обеспечение",
	"Your router can automatically detect firmware updates, but requires your authorization to install them. It is also possible to check for new firmware manually, upgrade firmware from a local file.": "Роутер может автоматически проверить наличие обновления программного обеспечения. Для установления требуется подтверждение обновления. Также возможно вручную обновить программное обеспечение из файла.",
	"Current Firmware Version": "Версия текущего программного обеспечения",
	"Current Firmware Date": "Дата текущего программного обеспечения",
	"Current Language Pack": "Текущий языковой пакет",
	"Download New Firmware": "Загрузить новое программное обеспечение",
	"Upgrade Firmware": "Обновить программное обеспечение",
	"Add a Language Pack": "Добавить языковой пакет",
	"Upload": "Выгрузить",
	"Upgrade": "Обновить",
	"Do you want to upgrade Firmware?": "Хотите обновить программное обеспечение?",
	"Do not power off the device until the Firmware Upgrade is complete!": "Не выключайте устройство до завершения процесса обновления программного обеспечения!",
	"Uploading Firmware": "Выполняется обновление программного обеспечения",
	"Firmware Upgrade failed!": "Ошибка обновления программного обеспечения!",
	"Firmware Upgrade success!": "Программное обеспечение успешно обновлено!",
	"Firmware Information": "Информация о программном обеспечении",
	"New Firmware Version": "Версия нового программного обеспечения",
	"New Firmware Date": "Дата нового программного обеспечения",
	"Check for New Firmware": "Проверить на наличие нового программного обеспечения",
	"Language Pack Information": "Информация о языковом пакете",
	"Current Language Pack": "Текущий языковой пакет",
	"Remove": "Удалить",
	"Upgrade Manually": "Обновить вручную",
	"Add a Language Pack": "Добавить языковой пакет",
	"Checking": "Выполняется проверка",
	"Retry": "Повторить",
	"This firmware is the latest version.": "Это последняя версия программного обеспечения.",
	"Downloading": "Выполняется загрузка",
	"Please do not close the browser while the firmware is being downloaded!": "Пожалуйста, не закрывайте браузер до окончания загрузки программного обеспечения!",
	"Upgrading": "Выполняется обновление",
	"Update Firmware": "Обновить программное обеспечение",


	"Statistics": "Статистика",
	"This page gives you various statistics about data transmitted and received by your router through the Internet, on your wired network (LAN), and through your wireless networks.": "На данной странице отображена статистика об отправленных и полученных данных через Интернет, по проводной сети (LAN) и по беспроводным сетям.",
	"Clear": "Очистить",
	"Information: Your browser is not support HTML5, please upgrade your browser.": "Информация: Web-браузер не поддерживает HTML5, пожалуйста, обновите браузер.",
	"Sent (Tx)": "Отправлено",
	"Received (Rx)": "Получено",
	"Total Packets": "Общее количество пакетов",
	"Total KByte(s)": "Всего Кбит",
	"KByte/sec": "Кбайт/сек",
	"Session": "Сессия",

	"Router Not Found": "Маршрутизатор не найден",
	"Please enter an IP address.": "Пожалуйста, введите IP-адрес.",
	"Please enter an e-mail address.": "Пожалуйста, введите адрес электронной почты.",
	"Please enter your e-mail account name.": "Пожалуйста, введите имя учетной записи электронной почты.",
	"Please enter your e-mail password.": "Пожалуйста, введите пароль электронной почты.",
	"Please enter a Wi-Fi Name(SSID).": "Пожалуйста, введите название Wi-Fi (SSID).",
	"Please enter an IP address.": "Пожалуйста, введите IP-адрес.",
	"Please enter a subnet mask.": "Пожалуйста, введите маску подсети.",
	"Please enter a device name.": "Пожалуйста, введите название устройства.",
	"Please enter a name for your DLNA Media Server.": "Пожалуйста, введите название для DLNA медиа-сервера.",
	"Please enter a port number.": "Пожалуйста, введите номер порта.",
	"Please enter a name for this rule.": "Пожалуйста, введите название для этого правила.",
	"Please enter an IP address range.": "Пожалуйста, введите диапазон IP-адресов.",
	"Please enter a port range.": "Пожалуйста, введите диапазон портов.",
	"Please enter a valid IP address range. (e.g. 1.1.1.1-1.1.1.2)": "Пожалуйста, введите корректный диапазон IP-адресов. (например, 1.1.1.1-1.1.1.2)",
	"Please enter a valid port range. (e.g. 1000-1001)": "Пожалуйста, введите корректный диапазон портов. (например, 1000-1001)",
	"Please enter a valid port number.": "Пожалуйста, введите корректный номер порта.",
	"Please enter a netmask.": "Пожалуйста, введите маску сети.",
	"Please enter a gateway address.": "Пожалуйста, введите адрес шлюза.",
	"Please enter a Metric.": "Пожалуйста, введите метрику.",
	"Please enter a valid netmask. (e.g. 255.255.255.0)": "Пожалуйста, введите корректную маску сети. (например, 255.255.255.0)",
	"Please enter a valid gateway address. (e.g. 192.168.0.1)": "Пожалуйста, введите корректный адрес шлюза. (например, 192.168.0.1)",
	"Please enter a destination network IP address.": "Пожалуйста, введите IP-адрес назначения.",
	"Please enter a prefix length.": "Пожалуйста, введите длину префикса.",
	"Please enter a valid IPv6 address. (e.g. 2001::1)": "Пожалуйста, введите корректный IPv6-адрес. (например, 2001::1)",
	"Please enter a valid destination network IP address. (e.g. 2001::)": "Пожалуйста, введите действительный IP-адрес сети назначения. (например, 2001::)",
	"Please enter an SMTP server address.": "Пожалуйста, введите адрес SMTP-сервера.",
	"Please enter a valid IP address. (e.g. 192.168.0.1)": "Пожалуйста, введите корректный IP-адрес. (например, 192.168.0.1)",
	"Please enter a valid IP address. (e.g. 255.255.255.0)": "Пожалуйста, введите корректный IP-адрес. (e.g. 255.255.255.0)",
	"Please enter a username.": "Пожалуйста, введите имя пользователя.",
	"Please enter a password.": "Пожалуйста, введите пароль.",
	"Please enter a valid e-mail.": "Пожалуйста, введите корректный адрес e-mail.",
	"Please enter a host name.": "Пожалуйста, введите имя узла. ",
	"Please enter a source network IP address.": "Пожалуйста, введите IP-адрес сети источника.",
	"Please enter a valid IPv6 address range (e.g., 2001::1-2001::2)": "Пожалуйста, введите корректный диапазон IP-адресов (например, 2001::1-2001::2)",
	"Your password must be 13 characters length": "Пароль должен содержать 13 символов",
	"Your password must be between 8-63 characters length": "Пароль должен содержать от 8 до 63 символов",
	"Your password must be between 6-15 characters length": "Пароль должен содержать от 6 до 15 символов",
	"Text field contains illegal characters.": "Текстовое поле содержит некорректные символы.",
	"Please enter a value between 0 and FF": "Пожалуйста, введите значение от 0 до FF",
	"End range must be greater than the start range": "Конечный IP-адрес диапазона должен быть больше начального",
	"Please enter a value": "Пожалуйста, введите значение",
	"Please enter an IPv6 address.": "Пожалуйста, введите IPv6-адрес.",
	"IPv4 Connection Type must to be PPPoE Session": "Соединение IPv4 возможно только при открытой PPPoE-сессии",
	"You should choose another IPv4 Internet Connection mode rather than 'DS-Lite' to access the Internet.": "Вы должны выбрать другой IPv4 Интернет режим соединения, кроме 'DS-Lite', для доступа в Интернет.",
	"Name cannot be the same.": "Имя не может быть таким же.",
	"Rule cannot be the same.": "Правило не может быть таким же.",
	"IP address cannot be the same.": "IP-адрес не может быть таким же.",
	"Please enter a server address.": "Пожалуйста, введите адрес сервера.",



	"err_required": "Пожалуйста, введите IP-адрес.",
	"err_email": "Пожалуйста, введите адрес электронной почты.",
	"err_email_AccountName": "Пожалуйста, введите имя учетной записи электронной почты.",
	"err_email_Password": "Пожалуйста, введите пароль электронной почты.",
	"err_ssid": "Пожалуйста, введите имя Wi-Fi (SSID).",
	"err_ip": "Пожалуйста, введите IP-адрес.",
	"err_subnet_Mask": "Пожалуйста, введите маску подсети.",
	"err_device_Name": "Пожалуйста, введите имя устройства.",
	"err_dlna_Name": "Пожалуйста, введите имя для DLNA медиа-сервера.",
	"err_port": "Пожалуйста, введите номер порта.",
	"err_protocol_Num": "Пожалуйста, введите номер протокола.",
	"err_rule_Name": "Пожалуйста, введите имя для этого правила.",
	"err_ip_Range": "Пожалуйста, введите диапазон IP-адресов.",
	"err_port_Range": "Пожалуйста, введите диапазон портов.",
	"err_address_CheckRange": "Пожалуйста, введите корректный диапазон IP-адресов. (например, 1.1.1.1-1.1.1.2)",
	"err_port_CheckRange": "Пожалуйста, введите корректный диапазон портов. (например, 1000-1001)",
	"err_port_Check": "Пожалуйста, введите корректный номер порта.",
	"err_netmask": "Пожалуйста, введите маску сети.",
	"err_gateway_Address": "Пожалуйста, введите адрес шлюза.",
	"err_matrix": "Пожалуйста, введите матрицу.",
	"err_netmask_Check": "Пожалуйста, введите корректную маску сети. (например, 255.255.255.0)",
	"err_gateway_AddressCheck": "Пожалуйста, введите корректный адрес шлюза. (например, 192.168.0.1)",
	"err_destinationIP": "Пожалуйста, введите IP-адрес назначения.",
	"err_prefix_Length": "Пожалуйста, введите длину префикса.",
	"err_ipv6address_Check": "Пожалуйста, введите корректный IPv6-адрес. (например, 2001::1)",
	"err_ipv6networkaddress_Check": "Пожалуйста, введите действительный IP-адрес сети назначения. (например, 2001::)",
	"err_smtp": "Пожалуйста, введите адрес SMTP-сервера.",
	"err_address_Check": "Пожалуйста, введите корректный IP-адрес. (например, 192.168.0.1)",
	"err_address_CheckAllRange": "Пожалуйста, введите корректный IP-адрес. (e.g. 255.255.255.0)",
	"err_check_UserName": "Пожалуйста, введите имя пользователя.",
	"err_check_Password": "Пожалуйста, введите пароль.",
	"err_email_Check": "Пожалуйста, введите корректный адрес e-mail.",
	"err_host_Name": "Пожалуйста, введите имя узла. ",
	"err_sourceIP": "Пожалуйста, введите IP-адрес сети источника.",
	"err_ipv6address_CheckRange": "Пожалуйста, введите корректный диапазон IP-адресов (например, 2001::1-2001::2",
	"err_password_WEPCheck": "Пароль должен содержать 13 символов",
	"err_password_WPACheck": "Пароль должен содержать от 8 до 63 символов",
	"err_check_DeviceAdminPassword": "Пароль должен содержать от 6 до 15 символов",
	"err_check_IllegalChar": "Текстовое поле содержит некорректные символы.",
	"err_hex_Range": "Пожалуйста, введите значение от 0 до FF",
	"err_range_Compare": "Конечный IP-адрес диапазона должен быть больше начального",
	"err_number": "Пожалуйста, введите значение",
	"err_ipv6": "Пожалуйста, введите IPv6-адрес.",
	"err_ipv6_PPPoE_Type": "Соединение IPv4 возможно только при открытой PPPoE-сессии",
	"err_ipv6_DsLite_Type": "Вы должны выбрать другой IPv4 Интернет режим соединения, а не 'DS-Lite' для доступа в Интернет.",
	"err_wan_lan_conflict": "Подсеть LAN конфликтует с подсетью WAN.",
	"err_Check_Mac": "Please enter a valid MAC address.",
	"err_mac_conflict": "The MAC address has existed.",
	"err_no_server_address": "Пожалуйста, введите адрес сервера.",
	"err_check_GuestZone": "IP conflicts with Guest Zone.",
	"err_qos": "Please enter a valid linkup speed. (e.g. 1~1000 Mbps)",

	"Features": "Функции",
	"Device Mode": "Режим устройства",
	"Router Mode": "Режим маршутизатора",
	"Bridge Mode": "Режим моста",
	"The device is changing to bridge mode.": "Выполняется переключение в режим моста.",
	"The device is changing to router mode.": "Выполняется переключение в режим маршрутизатора.",
	"The device is changing to ap mode.": "Устройство переходит в режим ТД.",
	"Station": "Станция",
	"Wireless Network Name": "Имя беспроводной сети",
	"Security": "Безопасность",
	"Scan": "Сканировать",
	"Your changes are being saved.": "Выполняется сохранение настроек.",


	"<b>Note</b>: If you are using a PPPoE connection, you will need to remove or disable any PPPoE client software running on your computers.": "<b>Примечание</b>: Если используется PPPoE-соединение, то требуется удалить или выключить любое клиентское программное обеспечение PPPoE, запущенное на компьютерах.",
	"3G/4G Network": "Сеть 3G/4G",
	"Add Profile": "Добавить профиль",
	"Are you sure you want to change your Internet connection type?": "Уверены, что хотите изменить тип Интернет-соединения?",
	"Browse": "Обзор",
	"Country": "Страна",
	"DHCP Client": "DHCP-клиент",
	"Dial-up Number": "Номер дозвона",
	"Download New Firmware": "Загрузить новое программное обеспечение",
	"Dynamic PPPoE": "PPPoE + Динамический IP",
	"Guest Zone 5GHz Secondary": "Вторая гостевая сеть 5 ГГц",
	"Hotspot": "Hotspot",
	"Hotspot Network Name(SSID)": "Имя сети hotspot (SSID)",
	"Interface is not ready, please check again.": "Интерфейс не готов к работе. Пожалуйста, проверьте еще раз.",
	"Internet Profiles": "Профили Интернет",
	"Internet Profiles are networks you want the device to remember and reconnect to in the future. Profiles are created automatically the first time you connect to a particular network, and some profiles may require additional information from your Internet service provider.": "Профили Интернет - это настройки сети, которые устройство должно запомнить и подключаться в дальнейшем, используя их. Профили создаются автоматически при первом подключении к конкретной сети. Некоторые профили могут потребовать дополнительную информацию от провайдера.",
	"IP Address (Reserved)": "IP-адрес (зарезервирован)",
	"ISP": "ISP",
	"Profile Name": "Имя профиля",
	"SIM Card Status": "Статус SIM-карты",
	"The selected profile does not connect to Internet. Please recheck the configuration of the profile.": "Выбранный профиль не может подключиться к Интернет. Пожалуйста, проверьте повторно настройки профиля.",
	"The selected profile is not configured.": "Выбранный профиль не настроен.",
	"This page shows you your current firmware version and language pack, and allows you to check for and download new firmware. After downloading the firmware, you can then upgrade it by using the buttons below. If you are using a language pack, we recommend that you also get the latest version of the language pack when upgrading the firmware to ensure that any changes in the interface are shown correctly.": "На данной странице указана версия программного обеспечения и языковой пакет. Также на этой странице можно проверить, доступно ли новое программное обеспечение, и загрузить его. После загрузки программного обеспечения можно обновить его, используя кнопоки ниже. Если используется языковой пакет, при обновлении программного обеспечения рекомендуется также загрузить последнюю версию языкового пакета для того, чтобы все изменения отображались в интерфейсе корректно.",
	"Type": "Тип",
	"Use this section to configure your Internet Connection profiles. If you are not sure what settings to use, please contact your Internet Service Provider.": "Используйте этот раздел для настройки профилей Интернет-соединения. Если Вы не уверены, какие настройки следует использовать, пожалуйста, обратитесь к Вашему провайдеру.",
	"Wi-Fi 5GHz Secondary": "Вторая сеть Wi-Fi 5 ГГц",
	"Your setting would be take effect.": "Настройки сохранены.",
	"It will take effect after reconnecting": "Изменение вступит в силу после повторного подключения",
	"Fail.": "Ошибка",

	"Specify your internet speed provided by your ISP; for example 10Mbps Upload, 20 Mbps download. You can measure your uplink and downlink speed with a speed test service on the internet.": "Укажите скорость подключения к Интернет, предоставленную Вашим провайдером; например, скорость выгрузки 10 Мбит/с, скорость загрузки 20 Мбит/с. Скорость нисходящего и восходящего потока можно измерить с помощью соответствующего теста в Интернет.",
	"Bandwidth": "Полоса пропускания",
	"Uplink Speed(Mbps)": "Скорость на магистральном порту (Mbps)",
	"Downlink Speed(Mbps)": "Скорость загрузки (Mbps)",

	"Quick VPN": "Quick VPN",
	"Quickly and easily create a profile for secure remote access to a Local Area Network (LAN). This profile can be used to configure other devices to connect to your LAN via a secure VPN tunnel.": "Быстро и легко создайте профиль для защищенного удаленного доступа к сети LAN. Этот профиль может использоваться для настройки подключений других устройств к сети LAN через защищенный VPN-туннель.",
	"L2TP over IPSec": "L2TP over IPSec",
	"Authentication Protocol": "Протокол аутентификации",
	"The Router IP Address is belong to the lease pool of DHCP server.": "IP-адрес маршрутизатора принадлежит пулу аренд DHCP-сервера.",
	"Save Configuration To Local Hard Drive": "Сохранить конфигурацию на локальном жестком ",
	"Guest Zone Facebook Wi-Fi":"Гостевая зона Facebook Wi-Fi",
	"Enable Facebook Wi-Fi":"Включить Facebook Wi-Fi",
	"Configure Facebook Wi-Fi":"Настроить Facebook Wi-Fi",
	"DENY these IP addresses to associate":"ЗАПРЕТИТЬ подключение этим IP-адресам ",
	"ALLOW these IP addresses to associate":"РАЗРЕШИТЬ подключение этим IP-адресам ",
	"Policy":"Политика",
	"IP range":"Диапазон IP-адресов",
	"IP Address Range":"Диапазон IP-адресов",
	"Save and Pair Facebook Wi-Fi":"Сохранить и соединить с Facebook Wi-Fi",
	"Try again and check your Internet Connection":"Попробуйте еще раз и проверьте Ваше Интернет-соединение"
}
